// One explicit visual assignment for every stage; labels are learner-facing.
const entry = (engine, scenes) => ({ engine, scenes: scenes.split(" ") });
export const catalog = {
  anova: entry(
    "statistics",
    "groups groups groups partition ratio partition ratio table ratio contrasts interaction interaction interaction partition table groups",
  ),
  correlation: entry(
    "statistics",
    "scatter scatter scatter distribution deviations scatter scatter distribution causal scatter",
  ),
  "chi-square": entry(
    "statistics",
    "counts counts counts contributions distribution counts counts",
  ),
  "time-series-analysis": entry(
    "statistics",
    "series series components series differences lag forecast residuals forecast series",
  ),
  "probability-sampling": entry(
    "statistics",
    "sample density sample sampling sampling sampling sample sampling sampling",
  ),
  "confidence-hypothesis-testing": entry(
    "statistics",
    "interval interval interval power interval power interval interval interval",
  ),
  "multiple-linear-regression": entry(
    "multiple",
    "fit contributions fit fit contributions contributions coefficients scores coefficients",
  ),
  "polynomial-regression": entry(
    "regression-lab",
    "fit fit basis coefficients residuals scores scores fit",
  ),
  "regression-diagnostics": entry(
    "regression-lab",
    "residuals residuals influence diagnostic residuals residuals fit scores diagnostic",
  ),
  "bias-variance": entry(
    "regression-lab",
    "fit fit resamples decomposition scores scores folds folds folds bootstrap folds resamples",
  ),
  "model-selection": entry(
    "regression-lab",
    "scores coefficients subsets criteria coefficients coefficients coefficients scores components coefficients folds scores",
  ),
  "logistic-regression": entry(
    "classification",
    "boundary sigmoid sigmoid contributions loss boundary confusion roc coefficients final",
  ),
  knn: entry(
    "classification",
    "neighbors neighbors split neighbors distances neighbors distances votes boundary neighbors confusion tuning neighbors votes",
  ),
  lda: entry(
    "classification",
    "clouds clouds split clouds means covariance covariance means projection boundary scores confusion coefficients clouds boundary",
  ),
  qda: entry(
    "classification",
    "clouds split boundary covariance distances boundary confusion coefficients covariance boundary",
  ),
  "support-vector-machine": entry(
    "classification",
    "boundary boundary margin margin margin boundary split loss scores boundary kernel tuning confusion margin",
  ),
  "one-r": entry(
    "classification",
    "rules votes rules rules rules rules rules boundary split confusion rules rules",
  ),
  "imbalanced-classification": entry(
    "classification",
    "prevalence prevalence confusion confusion confusion prevalence final confusion prevalence",
  ),
  "regression-trees": entry(
    "tree-space",
    "fit split fit tree gain gain tree tree curve tree pruning fit fit curve fit tree",
  ),
  "classification-trees": entry(
    "tree-space",
    "boundary split tree gain gain gain tree boundary pruning curve tree confusion tree boundary boundary",
  ),
  "random-forest": entry(
    "tree-space",
    "votes bootstrap votes votes oob votes curve votes oob",
  ),
  "gradient-boosting": entry(
    "trees",
    "fit residuals additive curve curve fit curve additive additive",
  ),
  pca: entry(
    "unsupervised",
    "projection projection projection loadings projection projection scores scree projection reconstruction",
  ),
  "hierarchical-clustering": entry(
    "unsupervised",
    "clusters distances clusters linkage dendrogram dendrogram dendrogram clusters dendrogram",
  ),
  "neural-networks": entry(
    "neural",
    "network inputs pipeline neuron neuron activation forward loss backward update cycle training settings evaluation errors contract architecture network cycle",
  ),
  "deep-learning": entry(
    "neural",
    "task shortcut pipeline tensor neuron hierarchy cycle regularization architecture transfer evaluation contract",
  ),
  "data-leakage-pipelines": entry(
    "workflow",
    "timing pipeline means leakage pipeline timing nested report leakage",
  ),
  "missing-data-encoding": entry(
    "workflow",
    "missing encoding means mechanism missing encoding pipeline report encoding",
  ),
  "experimental-design": entry(
    "workflow",
    "estimand assignment clusters protocol design-effect threats protocol report clusters",
  ),
};
export const sceneLabels = {
  groups: "Compare the group spreads",
  partition: "Follow the variation",
  ratio: "Build the F ratio",
  table: "Read the calculation",
  contrasts: "Compare two groups",
  interaction: "Change a difference of differences",
  scatter: "Inspect paired observations",
  distribution: "Read the reference distribution",
  deviations: "Multiply the deviations",
  causal: "Compare explanations",
  counts: "Observed and expected counts",
  contributions: "Follow each contribution",
  series: "Read the ordered series",
  components: "Separate the components",
  differences: "Subtract a previous value",
  lag: "Compare shifted values",
  forecast: "Forecast from past information",
  residuals: "Inspect the errors",
  sample: "One sample, one estimate",
  density: "Area means probability",
  sampling: "Repeat the sampling process",
  interval: "Estimate and uncertainty",
  power: "Two specified reference models",
  fit: "Inspect the fitted prediction",
  coefficients: "Read the fitted weights",
  basis: "Build the input columns",
  scores: "Compare the calculations",
  influence: "Remove and restore one point",
  diagnostic: "Choose a diagnostic view",
  resamples: "Refit another training sample",
  decomposition: "Separate sources of squared error",
  folds: "Inspect a held-out fold",
  bootstrap: "Trace a bootstrap sample",
  subsets: "Count the candidate models",
  criteria: "Compare selection criteria",
  boundary: "Explore the decision surface",
  sigmoid: "Turn a score into a probability",
  loss: "Inspect the loss",
  confusion: "Count held-out decisions",
  roc: "Trace validation thresholds",
  final: "Lock and evaluate once",
  neighbors: "Move a query among training rows",
  split: "Keep the partitions separate",
  distances: "Inspect a distance receipt",
  votes: "Accumulate the predictions",
  tuning: "Compare development settings",
  clouds: "Compare class distributions",
  means: "Locate the class centers",
  covariance: "Inspect spread and orientation",
  projection: "Rotate the coordinate system",
  margin: "Inspect the signed margin",
  kernel: "Compare feature-space similarity",
  rules: "Read the one-feature rule",
  prevalence: "Follow the denominators",
  tree: "Follow the selected path",
  gain: "Measure split improvement",
  curve: "Compare training and validation",
  pruning: "Inspect complexity choices",
  oob: "Count only eligible voters",
  additive: "Add the scaled corrections",
  clusters: "Step through the merges",
  linkage: "Compare group-distance rules",
  dendrogram: "Read the merge history",
  loadings: "Read the direction weights",
  scree: "Count retained variance",
  reconstruction: "Project back to the inputs",
  network: "A fully computed small network",
  inputs: "One row becomes two inputs",
  pipeline: "Fit only on training data",
  neuron: "Trace products, sum, and activation",
  activation: "Change the nonlinear mapping",
  forward: "Follow the forward values",
  backward: "Gradients before updates",
  update: "Apply one simultaneous update",
  cycle: "Step, inspect, and rewind",
  training: "Compare learning curves",
  settings: "Control the learning process",
  evaluation: "Inspect validation decisions",
  errors: "Inspect one prediction error",
  contract: "Check the input contract",
  architecture: "One mechanism at a time",
  task: "Choose the output contract",
  shortcut: "Identify a dataset shortcut",
  tensor: "Count the tensor dimensions",
  hierarchy: "Compose transformations",
  regularization: "Training and evaluation differ",
  transfer: "Choose which parameters can change",
  timing: "What is known at prediction time?",
  leakage: "Trace the information crossing",
  nested: "One outer evaluation fold",
  report: "Read the analysis record",
  missing: "A blank is not a zero",
  encoding: "Choose category geometry",
  mechanism: "State the missingness assumption",
  estimand: "Define the comparison",
  assignment: "One realized allocation",
  protocol: "Follow the planned sequence",
  "design-effect": "Count independent information",
  threats: "Identify the broken comparison",
};
