export const topics = {
  anova: "Analysis of Variance (ANOVA)",
  "association-rules": "Association Rules",
  "bias-variance": "Bias-Variance Trade-Off & Resampling",
  "chi-square": "Chi-Square Test of Independence",
  "classification-trees": "Classification Trees",
  "confidence-hypothesis-testing": "Confidence Intervals & Hypothesis Testing",
  correlation: "Correlation",
  "data-leakage-pipelines": "Data Leakage & Pipelines",
  "deep-learning": "Deep Learning",
  "evaluation-metrics": "Evaluation Metrics",
  "experimental-design": "Experimental Design & Randomisation",
  "gradient-boosting": "Gradient Boosting",
  "hierarchical-clustering": "Hierarchical Clustering",
  "imbalanced-classification": "Imbalanced Classification",
  kmeans: "K-Means Clustering",
  knn: "K-Nearest Neighbors (KNN)",
  lda: "Linear Discriminant Analysis (LDA)",
  "logistic-regression": "Logistic Regression",
  "missing-data-encoding": "Missing Data & Encoding",
  "model-selection": "Model Selection & Regularization",
  "multiple-linear-regression": "Multiple Linear Regression",
  "naive-bayes": "Naive Bayes",
  "neural-networks": "Neural Networks",
  "one-r": "One-R",
  "polynomial-regression": "Polynomial Regression",
  pca: "Principal Component Analysis (PCA)",
  "probability-sampling": "Probability & Sampling Distributions",
  qda: "Quadratic Discriminant Analysis (QDA)",
  "random-forest": "Random Forest",
  "regression-diagnostics": "Regression Diagnostics",
  "regression-trees": "Regression Trees",
  "simple-linear-regression": "Simple Linear Regression",
  "support-vector-machine":
    "Support Vector Machines — Separate classes with breathing room",
  "time-series-analysis": "Time Series Analysis",
};
