/* Shared end-of-lesson checklist. Essential teaching lives in each lesson's source HTML. */
(() => {
  const slug = location.pathname.split('/').pop().replace('.html', '');
  const summaries = {
    'simple-linear-regression': ['Linear form, independent errors, and stable residual spread.', 'Curvature, influential observations, extrapolation, or changing variance.', 'Validate predictive performance on unseen data.', 'R² is not correctness, causality, or guaranteed usefulness.', 'Slope with units, interval, residual error, diagnostics, and prediction interval.'],
    'multiple-linear-regression': ['Correct form, independent errors, stable variance, and a defensible adjustment set.', 'Omitted variables, collinearity, interactions, nonlinearity, and influential cases.', 'Choose features and transformations within training folds.', 'Coefficients are adjusted associations unless a causal design justifies more.', 'Reference levels, interactions, VIFs, intervals, diagnostics, and validation error.'],
    'polynomial-regression': ['Correct functional family and observations that support the fitted range.', 'Boundary oscillation, high-degree instability, influence, and extrapolation.', 'Select degree by validation or cross-validation; use test data once.', 'Nonlinear in x does not mean nonlinear in coefficients.', 'Degree-selection procedure, scaling or basis, uncertainty, and final test result.'],
    'classification-trees': ['Representative observations and features available at prediction time.', 'Small leaves, unstable splits, conflicting labels, and distribution shift.', 'Choose depth and pruning through validation or cross-validation.', 'Impurity, probabilities, and categorical support depend on context and software.', 'Tree constraints, pruning rule, class metrics with uncertainty, and final test result.'],
    'logistic-regression': ['Appropriate link, independent observations, and a suitable linear predictor.', 'Separation, omitted nonlinearity, imbalance, poor calibration, and drift.', 'Tune regularisation, calibration, and threshold on validation data.', 'A 0.5 threshold is a convention; coefficients are conditional associations.', 'Solver, scaling, odds ratios with intervals, calibration, threshold, and metrics.'],
    knn: ['A meaningful distance and locally similar observations.', 'High dimensions, irrelevant variables, missingness, imbalance, and expensive prediction.', 'Fit scaling and imputation in folds; tune K and weighting on validation data.', 'Odd K only prevents equal votes in binary classification.', 'Distance, scaling, K, weighting, resampling, metrics, and uncertainty.'],
    pca: ['Numeric features, meaningful covariance geometry, and a justified scaling choice.', 'Target signal in low-variance directions, outliers, drift, or uninterpretable components.', 'Fit scaling and PCA inside training folds only.', 'Explained variance is not general information or predictive usefulness.', 'Scaling decision, loadings, explained sample variance, components retained, and stability.'],
    'model-selection': ['Candidate models and resampling scheme match the data structure.', 'Repeated comparison, unstable selection, rank deficiency, and correlated predictors.', 'Use nested CV or a final untouched test for unbiased evaluation.', 'Lasso selection is neither uniquely important nor causal.', 'Candidate set, full pipeline, selection rule, uncertainty, stability, and final performance.'],
    correlation: ['Paired independent observations and a relationship suited to the chosen coefficient.', 'Outliers, restriction of range, clusters, dependence, and non-monotonic form.', 'Use resampling that preserves groups or repeated observations.', 'A small p-value is not the probability the null is true or proof of causality.', 'Plot, n, coefficient, confidence interval, assumptions, and practical meaning.'],
    anova: ['Independent observations and assumptions appropriate to the ANOVA variant.', 'Unequal variance, dependence, strong non-normality, outliers, and multiplicity.', 'Analysis and resampling must respect the sampling or experimental design.', 'An omnibus p-value neither measures importance nor identifies differing groups.', 'Group estimates, intervals, ANOVA variant, effect size, contrasts, and correction.'],
    'chi-square': ['Independent counts and adequate expected cells for the approximation.', 'Sparse tables, repeated observations, structural zeros, and multiple cell inspection.', 'Confirm analysis choices without outcome-guided fishing.', 'Evidence against independence does not identify causality or important cells.', 'Table, expected counts, statistic, df, p-value, Cramér’s V, and residuals.'],
    'time-series-analysis': ['Stable features or explicit modelling of change and seasonality.', 'Structural breaks, non-stationarity, long horizons, and changing measurement.', 'Use chronological, expanding-window, or rolling-window evaluation—never random shuffling.', 'ACF bounds are approximate and lag patterns must be interpreted collectively.', 'Forecast horizon, split, baselines, errors with uncertainty, intervals, and residual diagnostics.'],
    kmeans: ['A distance and roughly centroid-shaped groups that suit the scientific question.', 'Outliers, unequal density or size, non-spherical groups, and unstable starts.', 'Fit scaling appropriately and examine resampled stability.', 'The elbow is a heuristic, not the true number of clusters.', 'Scaling, initialisation, restarts, K rationale, silhouette, and stability.'],
    'hierarchical-clustering': ['A justified distance-linkage combination and meaningful feature scale.', 'Chaining, outliers, scale dominance, and unstable dendrogram branches.', 'Assess stability under resampling and reasonable preprocessing choices.', 'Dendrogram heights differ in meaning across linkage methods.', 'Distance, linkage, scaling, cut rule, sensitivity, and cluster stability.'],
    qda: ['Class-conditional covariance estimates sufficiently supported by data.', 'Small classes, many features, singular covariance, outliers, and drift.', 'Choose the shrinkage target and amount within cross-validation.', 'Only shrinkage toward pooled covariance moves QDA directly toward LDA.', 'Priors, covariance treatment, regularisation, metrics, calibration, and uncertainty.'],
    'bias-variance': ['Squared-error decomposition at a fixed input across repeated training samples.', 'Using the exact algebra for unrelated losses or ignoring dependence in resampling.', 'Use data-appropriate CV and an outer evaluation when selection occurs.', 'Classification bias and variance need not share the same formula.', 'Loss, resampling design, fold distributions, selection rule, and final uncertainty.']
  };
  const values = summaries[slug];
  if (!values) return;
  const labels = ['Assumptions', 'When the method fails', 'Validation and leakage', 'Interpretation cautions', 'What to report'];
  const section = document.createElement('section');
  section.className = 'statml-rigor-panel';
  section.setAttribute('aria-label', 'Practical method checklist');
  section.innerHTML = `<p class="statml-rigor-kicker">Practical method checklist</p><h3>Before you finish</h3><div class="statml-rigor-grid">${labels.map((label, i) => `<div><h4>${label}</h4><p>${values[i]}</p></div>`).join('')}</div>`;
  const stages = [...document.querySelectorAll('[data-stage]')].filter(el => Number(el.dataset.stage) > 0);
  const last = stages.at(-1) || document.querySelector('main') || document.body;
  const knowledge = last.querySelector('.quiz-card,.knowledge-check,[data-knowledge-check]');
  if (knowledge) knowledge.insertAdjacentElement('beforebegin', section); else last.append(section);
})();
