/* Shared end-of-lesson checklist. Essential teaching lives in each lesson's source HTML. */
(() => {
  const slug = location.pathname.split('/').pop().replace('.html', '');
  const summaries = {
    'simple-linear-regression': ['A straight-line mean should suit the data. For the usual intervals, errors need independent observations and suitable spread assumptions.', 'Curves, unusual points, changing error spread or predictions far outside the observed range can cause trouble.', 'Check predictions on rows that did not fit the line.', 'A high R² describes training fit. It does not prove causation or useful future predictions.', 'Give the slope and its units, uncertainty intervals, error size and error plots. State how prediction intervals were made.'],
    'multiple-linear-regression': ['Choose inputs for a clear question. Check the model shape, independent observations and error assumptions.', 'Missing clues, almost repeated columns, curved effects and unusual rows can make the fitted weights misleading.', 'Choose inputs and transformations using training data within each fold, then check held-out rows.', 'A weight describes a model comparison with other inputs fixed. A cause-and-effect claim needs extra evidence.', 'State category reference groups and combined effects. Report weight intervals, checks for overlapping inputs, error plots and held-out error.'],
    'polynomial-regression': ['Use a curve family and input range supported by the observations.', 'High-degree curves can wiggle, change sharply near the edges and behave badly outside the observed range.', 'Choose degree with validation or cross-validation. Keep the final test for the finished choice.', 'The input can be squared or cubed while the weights still enter by multiplication and addition.', 'State how you chose degree, how columns were built or scaled, uncertainty and the final test result.'],
    'classification-trees': ['Training rows should represent the intended use. Every input must be known when predicting.', 'Tiny leaves, conflicting labels, unstable cuts or a changed population can hurt new predictions.', 'Choose depth and pruning with validation or cross-validation.', 'Check how the software measures mixed labels and handles categories. Small-leaf fractions can be unreliable probabilities.', 'Report growth limits, pruning choices, class error counts and rates, uncertainty and the final test result.'],
    'logistic-regression': ['The weighted-score and probability rule should suit the question. Check independence and whether input effects need extra terms.', 'A perfect training separation can make unpenalized weights unstable. Curved effects, rare classes or a changed population can also cause trouble.', 'Choose weight penalties, probability adjustments and decision cutoffs using development data.', 'A cutoff of 0.5 is a choice. Input weights describe adjusted model relationships, rather than proven causes.', 'State the fitting method, input scaling, odds multipliers with intervals, probability checks, cutoff and error rates.'],
    knn: ['Nearby points should tend to have similar labels under a meaningful distance rule.', 'Too many inputs, irrelevant clues, missing values, rare classes or slow neighbour searches can cause trouble.', 'Learn scales and fill values inside each training fold. Choose K and vote weights using development data.', 'Odd K avoids equal class counts only for two classes with equal-weight votes. Weighted votes and more classes can still tie.', 'Report the distance, scales, K, vote weights, evaluation splits, error rates and uncertainty.'],
    pca: ['Use numeric inputs and a scale choice that makes their joint spread meaningful.', 'Useful outcome clues may lie in small-variance directions. Unusual points or changing input patterns can also alter the axes.', 'When checking predictions, learn scales and PCA using only each fold’s training rows.', 'Retained variance measures input spread. It does not guarantee retained meaning or useful predictions.', 'Report scaling, direction weights, variance shares, kept components and how stable the directions are.'],
    'model-selection': ['Compare suitable candidates using splits that respect related people, groups or time.', 'Trying many models can find lucky scores. Almost repeated inputs and small samples can also make the chosen model unstable.', 'Keep an outer evaluation or final test outside all model choices. Match that evaluation to the intended use.', 'A Lasso weight of zero does not prove that an input is uniquely unimportant or has no causal effect.', 'Record all candidates, input preparation, the choosing rule, uncertainty, stability and final performance.'],
    correlation: ['Pair the two values from each observation. Use a correlation measure suited to the relationship and sampling design.', 'Unusual points, a narrow input range, grouped observations or curved patterns can change the result.', 'When resampling, keep related groups or repeated measurements together as the design requires.', 'A small p-value does not give the chance that the null is true or show which variable causes another.', 'Show the scatterplot, sample size, correlation, interval, assumptions and what the size means in practice.'],
    anova: ['Use an ANOVA method whose spread and shape assumptions suit the independent units in the study.', 'Unequal spreads, related rows, unusual outcomes or many follow-up comparisons can make a simple analysis unreliable.', 'Fit the analysis and any resampling to how people or groups were actually sampled or assigned.', 'The overall p-value does not measure effect size or tell us which pairs differ.', 'Report group averages and intervals, the ANOVA method, effect size, planned comparisons and any multiple-comparison adjustment.'],
    'chi-square': ['Count independent observations. Expected cell counts must support the chi-square approximation.', 'Tiny expected counts, repeated people, impossible cells or many unplanned cell checks can cause trouble.', 'Choose the question and analysis before selecting whichever cells look most striking.', 'Evidence against independence shows a relationship. It does not prove a cause or identify useful cells by itself.', 'Show observed and expected counts, χ², degrees of freedom, p-value and Cramér’s V. Use cell residuals to explain gaps.'],
    'time-series-analysis': ['Use past information and a model that handles the relevant trend, seasonality or changes.', 'A changed process, measurement method or long forecast horizon can make old patterns unreliable.', 'Check later periods using only earlier data, with moving or growing training windows. Keep future observations out of preparation.', 'Autocorrelation summaries and their bounds are approximate. Read patterns across lags with the data’s context.', 'Report the steps ahead, chronological splits, simple forecast comparison, errors and uncertainty. Explain intervals and check remaining error patterns.'],
    kmeans: ['The distance and compact, centre-based groups should suit the question and input units.', 'Unusual points, curved groups, uneven density or different starting centres can give poor groupings.', 'Choose scaling for the intended use. Check how groups change across resampled data and different starts.', 'An elbow is a clue to discuss, rather than proof of the true number of groups.', 'Report scales, starting method, repeated starts and your reason for K. Check separation from other groups and stability.'],
    'hierarchical-clustering': ['Choose input scales, distances and a group-comparison rule that fit the question.', 'A chain of nearby points, unusual observations or a dominant input scale can create fragile branches.', 'Compare sensible preparation choices and resampled data to check whether the groups persist.', 'A tree’s merge height means different things under different linkage rules. Leaf spacing is just layout.', 'Report distance, linkage, scales and where you cut the tree. Describe sensitivity and group stability.'],
    qda: ['Each class needs enough rows to estimate its own joint spread across the inputs.', 'Small classes, many inputs, nearly repeated columns, unusual rows or changing patterns can make those estimates unstable.', 'Use cross-validation to choose how much to pull spread estimates toward a chosen stable target.', 'Pulling both classes toward a pooled spread moves QDA toward LDA. Other shrinkage targets do something different.', 'State class priors, spread estimates and stabilization. Report error rates, probability checks and uncertainty.'],
    'bias-variance': ['The displayed formula uses squared error at one fixed input across repeated training samples.', 'Other loss rules need other reasoning. Resampling that ignores related observations can also mislead.', 'Use splits suited to the data. Keep an outer check separate when the inner results choose a model.', 'Do not apply this squared-error formula unchanged to every classification loss.', 'State the loss rule, resampling plan, spread of fold results, choosing rule and final uncertainty.']
  };
  const values = summaries[slug];
  if (!values) return;
  const labels = ['Assumptions', 'When the method fails', 'Validation and leakage', 'Interpretation cautions', 'What to report'];
  const section = document.createElement('section');
  section.className = 'statml-rigor-panel';
  section.setAttribute('aria-label', 'Practical method checklist');
  section.innerHTML = `<p class="statml-rigor-kicker">Practical method checklist</p><h3>Before you finish</h3><div class="statml-rigor-grid">${labels.map((label, i) => `<div><h4>${label}</h4><p>${values[i]}</p></div>`).join('')}</div>`;
  const stages = [...document.querySelectorAll('[data-stage]')].filter(el => Number(el.dataset.stage) > 0);
  const last = stages.at(-1) || document.querySelector('main') || document.body;
  const knowledge = last.querySelector('.quiz-card,.knowledge-check,[data-knowledge-check]');
  if (knowledge) knowledge.insertAdjacentElement('beforebegin', section); else last.append(section);
})();
