(() => {
const lessons = {
'evaluation-metrics':{title:'Evaluation Metrics',badge:'Model Evaluation · Foundations',intro:'Choose metrics from the real consequences of errors—not from whichever score looks healthiest.',outcomes:['Match metrics to decisions','Separate discrimination from calibration','Report uncertainty'],sections:[
['What problem does this solve?','A metric translates prediction errors into a decision-relevant summary. No single metric is best for every use case.'],
['Regression metrics','<ul><li><b>MAE</b> weights absolute errors equally and stays in outcome units.</li><li><b>MSE/RMSE</b> penalise large errors more; RMSE returns to outcome units.</li><li><b>Out-of-sample R²</b> compares against a mean baseline and can be negative.</li><li><b>MAPE</b> breaks near zero and is asymmetric.</li></ul><p class="callout">If underprediction costs more than overprediction, use an asymmetric loss that reflects that cost.</p>'],
['Classification metrics','<ul><li>Accuracy needs plausible class balance and equal error costs.</li><li>Precision, recall, specificity and F1 answer different questions.</li><li>ROC-AUC ranks across thresholds; PR-AUC is often more revealing with rare positives.</li><li>Log loss and Brier score evaluate probabilities; calibration asks whether predicted risks match frequencies.</li></ul>'],
['Evaluation workflow','Choose the metric before comparing models. Tune on validation data, evaluate once on the test set, and use bootstrap or repeated-CV intervals. Always compare against a meaningful baseline.'],
['What to report','<p class="callout report">Report the metric definition, decision threshold, class prevalence or outcome scale, baseline, point estimate, uncertainty interval, and real-world error costs.</p>']]},
'data-leakage-pipelines':{title:'Data Leakage & Pipelines',badge:'Model Evaluation · Workflow',intro:'Keep information from validation, test, groups, and the future out of model development.',outcomes:['Recognise leakage','Build fold-safe pipelines','Choose valid resampling'],sections:[
['The site-wide rule','<p class="callout"><b>Any step that learns from data must be fitted using training data only.</b></p><p>This includes scaling, imputation, feature selection, PCA, frequency-based encoding, outlier thresholds, oversampling and threshold tuning.</p>'],
['A safe pipeline','Split first. Within each training fold: fit imputation → encoding → scaling → feature selection/PCA → model. Apply the learned transformations to that fold’s validation rows. Lock everything before the final test.'],
['Hidden leakage','Target leakage uses variables unavailable at prediction time. Group leakage puts the same person or organisation in train and validation. Time leakage lets future values predict the past. Duplicate records can cross splits.'],
['Choose resampling','Use stratified CV for imbalance, grouped CV for repeated entities, time-series CV for ordered data, nested CV for selection plus unbiased evaluation, and repeated CV for more stable estimates.'],
['Practical checklist','<ul><li>Can this feature exist at prediction time?</li><li>Did any preprocessing see held-out rows?</li><li>Can related observations cross folds?</li><li>Was the test set inspected more than once?</li></ul>']]},
'regression-diagnostics':{title:'Regression Diagnostics',badge:'Regression · Foundations',intro:'Decide when coefficient, interval, and prediction claims deserve trust.',outcomes:['Read residual plots','Diagnose influence and collinearity','Distinguish interval types'],sections:[
['Assumptions','Check correct functional form, independent errors, constant residual variance, and—when classical small-sample inference relies on it—residual normality. These assumptions concern errors and design, not merely the raw outcome.'],
['Diagnostic views','Residual-versus-fitted plots reveal curvature and heteroscedasticity. Q–Q plots assess tail departures. Leverage finds unusual predictor combinations; Cook’s distance combines leverage and residual size to flag influence.'],
['Sensitivity','Refit after investigating influential cases, but do not delete observations merely to improve significance. Use robust standard errors or a variance model when heteroscedasticity is scientifically plausible.'],
['Multiple regression','Inspect VIFs and coefficient intervals for multicollinearity. Encode categories with clear reference groups, include justified interactions, and describe coefficients as adjusted associations rather than causal effects.'],
['Intervals and reporting','A confidence interval concerns an estimated mean; a prediction interval concerns a new outcome and is wider. Report assumptions, diagnostic findings, coefficient intervals, residual standard error, validation performance and sensitivity analyses.']]},
'probability-sampling':{title:'Probability & Sampling Distributions',badge:'Statistics · Foundations',intro:'Connect random variables, distributions, samples, and standard errors.',outcomes:['Model uncertainty','Understand repeated sampling','Interpret standard error'],sections:[
['Probability and random variables','A random variable maps outcomes to numbers. Discrete variables use probability masses; continuous variables use densities whose areas—not point heights—represent probability.'],
['Common distributions','Bernoulli/binomial model binary counts, normal models symmetric continuous variation, t handles estimated scale in mean inference, chi-square models sums of squared normals, and Poisson models event counts under restrictive rate assumptions.'],
['Sampling distributions','Imagine repeating the study under the same design. The sampling distribution describes how a statistic changes across those samples; it is not the distribution of individual observations.'],
['Standard error','The standard error is the estimated standard deviation of a statistic’s sampling distribution. It usually shrinks with more independent information, often near 1/√n, but clustering and dependence reduce effective sample size.'],
['Why this matters','Confidence intervals and tests are calibrated across repeated samples under assumptions. Always identify the population, sampling mechanism, dependence structure and estimand.']]},
'confidence-hypothesis-testing':{title:'Confidence Intervals & Hypothesis Testing',badge:'Statistics · Inference',intro:'Use compatible intervals, tests, effect sizes, and decision rules without overclaiming.',outcomes:['Interpret p-values correctly','Read confidence intervals','Control multiplicity'],sections:[
['Confidence intervals','A 95% procedure captures the true parameter in 95% of repeated samples under its assumptions. For one realised interval, avoid saying there is a 95% frequentist probability the fixed parameter lies inside.'],
['P-values','<p class="callout">A small p-value indicates that the observed result would be unusual under the null hypothesis, assuming the model assumptions hold.</p><p>It is not the probability the null is true, the probability the result happened by chance, practical importance, or proof of causality.</p>'],
['Testing workflow','Pre-specify H₀, H₁, α, outcome and analysis. Check assumptions; compute the estimate, effect size, interval and p-value; then interpret in context. Failing to reject is not proving no effect.'],
['Power and multiplicity','Power depends on effect size, noise, sample size and design. Many tests inflate false positives; use planned hypotheses and family-wise or false-discovery-rate corrections as appropriate.'],
['Related methods','Use paired or independent t-tests according to design; Welch’s test for unequal variances; permutation or rank methods when their estimands and assumptions fit. Report practical significance.']]},
'random-forest':{title:'Random Forest',badge:'Machine Learning · Ensembles',intro:'Average decorrelated decision trees to improve prediction stability.',outcomes:['Understand bagging','Tune without leakage','Interpret cautiously'],sections:[
['How it works','Each tree trains on a bootstrap sample and considers a random subset of features at each split. Averaging reduces variance when trees are imperfectly correlated.'],
['Evaluation','Out-of-bag predictions can estimate performance during development, but do not replace a locked final evaluation when extensive tuning occurred. Tune tree count, feature sampling, depth and leaf size inside validation.'],
['Failure modes','Forests can be large, poorly calibrated, biased by certain importance measures, and weak at extrapolating regression trends. Correlated predictors share or mask importance.'],
['Interpretation','Permutation importance measures predictive reliance, not causality. Partial-dependence plots average over data and can be misleading with correlated features; consider conditional or local alternatives.'],
['What to report','Pipeline, resampling, hyperparameters, class weighting, calibration, baseline comparisons, uncertainty and stability of importance rankings.']]},
'gradient-boosting':{title:'Gradient Boosting',badge:'Machine Learning · Ensembles',intro:'Build an additive model by repeatedly correcting current prediction errors.',outcomes:['Understand boosting','Regularise complexity','Validate early stopping'],sections:[
['Objective','At each round, a weak learner approximates the negative gradient of a chosen loss. Learning rate and number of rounds work together; shallow trees often capture controlled interactions.'],
['Regularisation','Control depth/leaves, learning rate, row and feature subsampling, minimum leaf size and penalties. More rounds are not automatically better.'],
['Validation','Choose hyperparameters and early stopping on validation data inside the development process. Preprocessing belongs inside folds; evaluate the locked pipeline once on test data.'],
['Probability quality','A strong ranking model may be poorly calibrated. Check log loss, Brier score and calibration as well as ROC-AUC or PR-AUC; choose thresholds from costs.'],
['Failure modes','Boosting can chase noise, mishandle distribution shift, and yield misleading importance under correlation. Compare with simple baselines and report resampling distributions.']]},
'missing-data-encoding':{title:'Missing Data & Encoding',badge:'Data Preparation · Workflow',intro:'Treat missingness and categories as modelling choices, not housekeeping.',outcomes:['Diagnose missingness','Encode categories safely','Prevent preprocessing leakage'],sections:[
['Missingness mechanisms','MCAR, MAR and MNAR are assumptions about why values are missing, not labels a plot can prove. Record structural missingness separately from accidental absence.'],
['Imputation','Fit imputation on training folds only. Simple imputation may be adequate for prediction; multiple imputation is often needed for valid inferential uncertainty. Missingness indicators can help when absence is informative.'],
['Categorical encoding','One-hot encoding needs a reference convention; ordinal encoding requires a defensible order; target/frequency encoding must be cross-fitted to avoid leakage. Define behaviour for unseen categories.'],
['Operational safeguards','Keep a data dictionary, retain raw values, validate ranges and types, and place every learned transform in a reproducible pipeline.'],
['What to report','Missingness rates and patterns, assumptions, imputation model, number of imputations where relevant, category handling, unseen-level policy and sensitivity analyses.']]},
'imbalanced-classification':{title:'Imbalanced Classification',badge:'Machine Learning · Classification',intro:'Evaluate rare outcomes using realistic prevalence, costs, and calibrated probabilities.',outcomes:['Reject accuracy traps','Tune thresholds by cost','Resample safely'],sections:[
['Start with the decision','Define the positive class, prevalence, cost of false positives and false negatives, and intervention capacity before choosing metrics or thresholds.'],
['Metrics','Accuracy can hide failure on rare classes. Report confusion counts, precision, recall, specificity, PR-AUC and calibrated probabilities; ROC-AUC can look optimistic when negatives dominate.'],
['Training options','Class weights change the fitting objective. Under/oversampling and synthetic methods can help but must occur inside training folds only. They can distort apparent prevalence and calibration.'],
['Thresholds and calibration','Select thresholds on validation data using explicit costs or constraints. Recalibrate when sampling or weighting changes probability meaning, then evaluate once on the final test set.'],
['Uncertainty and drift','Rare-event metrics are unstable. Use stratified resampling with intervals, preserve groups and time structure, and monitor prevalence and calibration after deployment.']]},
'experimental-design':{title:'Experimental Design & Randomisation',badge:'Statistics · Study Design',intro:'Build causal credibility before collecting data.',outcomes:['Define estimands','Use randomisation','Plan power and analysis'],sections:[
['Question and estimand','Specify population, treatment, comparator, outcome, time horizon and causal contrast. The analysis should estimate that quantity—not a convenient surrogate.'],
['Randomisation and controls','Random assignment balances confounders in expectation. Use allocation concealment, appropriate controls and blinding where possible; blocking or stratification can improve precision.'],
['Dependence and interference','Clustered, repeated and paired designs require matching analysis. Standard errors that ignore dependence are too small. Interference violates the assumption that one unit’s treatment does not affect another’s outcome.'],
['Power and multiplicity','Plan sample size from a meaningful effect, variance, attrition and design effect. Pre-specify primary outcomes and multiplicity control; exploratory analyses should be labelled.'],
['What to report','Protocol, randomisation, exclusions, missing data, adherence, effect estimates with confidence intervals, harms, deviations and practical significance. Statistical significance alone is not success.']]}
};
const slug=location.pathname.split('/').pop().replace('.html','');const d=lessons[slug];if(!d)return;document.title=`${d.title} · StatML Academy`;
document.body.innerHTML=`<header class="hero"><a class="home" href="../index.html">← StatML Academy</a><div class="eyebrow">${d.badge}</div><h1>${d.title}</h1><p>${d.intro}</p><div class="outcomes">${d.outcomes.map(x=>`<span>${x}</span>`).join('')}</div></header><main class="shell"><article class="lesson">${d.sections.map((s,i)=>`<section class="stage" id="stage-${i+1}"><p class="stage-label">Stage ${String(i+1).padStart(2,'0')}</p><h2>${s[0]}</h2><div>${s[1]}</div></section>`).join('')}<section class="stage"><p class="stage-label">Knowledge check</p><h2>Would another reasonable sample change the conclusion?</h2><div class="check"><button type="button">Reveal the reporting test</button><p class="answer">A defensible answer names the estimand, assumptions, data split or design, effect size, uncertainty, practical consequence, and the most plausible failure mode.</p></div></section></article><nav class="map"><strong>Lesson map</strong>${d.sections.map((s,i)=>`<a href="#stage-${i+1}">${String(i+1).padStart(2,'0')} · ${s[0]}</a>`).join('')}</nav></main>`;document.querySelector('.check button').addEventListener('click',e=>e.currentTarget.parentElement.classList.toggle('revealed'));
})();
