/* Author content here, then run npm run generate:pilots. HTML stays readable without JS. */
const table = (heads, rows) =>
  `<div class="table-wrap"><table><thead><tr>${heads.map((h) => `<th scope="col">${h}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((c, i) => (i ? `<td>${c}</td>` : `<th scope="row">${c}</th>`)).join("")}</tr>`).join("")}</tbody></table></div>`;
const live = (key, text) => `<span data-bind="${key}">${text}</span>`;
const s = (
  title,
  question,
  answer,
  receipt,
  experiment,
  why,
  check,
  solution,
) => ({ title, question, answer, receipt, experiment, why, check, solution });
export const pilots = {
  "simple-linear-regression": {
    title: "Simple Linear Regression",
    family: "Supervised learning · Regression",
    accent: "blue",
    intro:
      "One line. Five students. A surprisingly useful way to think about prediction.",
    prerequisite: "Means, coordinates and a little algebra",
    next: "Regression Diagnostics",
    nextSlug: "regression-diagnostics",
    summary:
      "Move a line, inspect its mistakes, then discover why least squares chooses one particular fit.",
    stages: [
      s(
        "The editable reality",
        "What is the line trying to explain?",
        "Each dot is one student. We use study hours, x, to predict score, y. The line describes an average pattern in these five examples. It does not say every student follows the line exactly.",
        `<div class="receipt-label">Our tiny dataset · edit a value</div>${table(
          ["Student", "Hours x", "Score y"],
          [50, 55, 61, 64, 70].map((y, i) => [
            "ABCDE"[i],
            `<input class="cell-input" aria-label="Student ${"ABCDE"[i]} hours" type="number" min="0" max="10" step="0.5" value="${i + 1}" data-point="${"ABCDE"[i]}" data-field="x">`,
            `<input class="cell-input" aria-label="Student ${"ABCDE"[i]} score" type="number" min="0" max="100" value="${y}" data-point="${"ABCDE"[i]}" data-field="y">`,
          ]),
        )}<p class="mini-note">Five observations illustrate the calculation. They cannot establish that studying caused a higher score.</p>`,
        "Change C’s score from 61 to 80. Which part of the pattern changed?",
        "A row is one measured student. An input is a clue available when we predict; the target is the score we want to predict. The population mean model is E[y|x]=β₀+β₁x, meaning average y at a given x. Individual scores vary around it. Here all five rows are used to show training arithmetic. A predictive claim needs separate evaluation data. Other factors, such as prior preparation, could affect both hours and scores.",
        "If two students study for three hours, must their scores match?",
        "No. The line estimates a mean response. Individual scores can differ because of other influences and random variation.",
      ),
      s(
        "Make your guess",
        "What do slope and intercept actually do?",
        "Slope controls the line's tilt. It tells us the predicted score change for one extra study hour. Intercept moves the line up or down. It is the prediction at zero hours.",
        `<div class="formula">ŷ = b + mx</div>${table(
          ["Part", "Read it aloud"],
          [
            ["m = slope", "Score points per extra hour"],
            ["b = intercept", "Predicted score at zero hours"],
            ["ŷ = prediction", "Where the line sits at this x"],
          ],
        )}<p>Your current line: <strong>${live("equation", "ŷ = 40.0 + 7.0x")}</strong></p>`,
        "Change only the slope. Then change only the intercept. Watch which movement each controls.",
        "ŷ means predicted y; the small hat marks an estimate. In ŷ=b+mx, m is slope and b intercept. Slope has score-points per hour; intercept has score-points. Negative slope is allowed. If zero hours is outside the data, the intercept may lack a useful real-world interpretation. The trial line is a choice to inspect, not necessarily the fitted best line.",
        "With slope 7, what does two more hours change in the prediction?",
        "The prediction rises by 14 score points. This is a model-based association, not a guaranteed individual improvement.",
      ),
      s(
        "Measuring the mistakes",
        "How wrong is one prediction?",
        "A residual is actual score minus predicted score. It is the vertical gap from the line to the dot. Above the line means a positive gap; below means a negative one.",
        `<div class="receipt-label">Selected student ${live("student", "D")} · live calculation</div>${table(
          ["Step", "Value"],
          [
            ["Actual y", live("actual", "64.0")],
            ["Predicted ŷ", live("predicted", "68.0")],
            ["Residual y − ŷ", live("residual", "−4.0")],
          ],
        )}<p class="mini-note">Select a dot, or use the student selector in the visual.</p>`,
        "Select two students on opposite sides of your line. Compare the residual signs.",
        "For actual 61 and predicted 65, residual is −4: the prediction was four points too high. A residual +4 means four points too low. Least squares measures vertical outcome gaps at fixed x. It does not minimize the shortest diagonal distance to the line, which is a different fitting problem. Residuals are observed fitting errors, not the unobserved population disturbances themselves.",
        "The actual score is 61 and the predicted score is 65. What is the residual?",
        "61 − 65 = −4. The model overpredicted by four points.",
      ),
      s(
        "A penalty that cannot cancel",
        "Why square the errors?",
        "Errors of +4 and −4 add to zero, hiding two mistakes. Squaring means multiplying each error by itself. Both now contribute 16. Large errors get much larger penalties.",
        `${table(["Residuals", "Signed sum", "Squared sum"], [["+4 and −4", "0", "16 + 16 = 32"]])}<p>Current SSE: <strong>${live("sse", "51.0")}</strong> score-points².<br>Current MAE: <strong>${live("mae", "2.6")}</strong> score points.</p>`,
        "Compare each signed error with its square. Add the five squared values and check SSE. Why does a negative error still increase this total?",
        "SSE means sum of squared errors: add every (actual−predicted)². Σ means add over rows. MAE instead averages error sizes without squaring; it uses a different fitting objective and is less dominated by large misses. The drawing's square tile area represents squared error, not another input coordinate. SSE has squared score units; RMSE and residual standard error return to score units.",
        "Which contributes more to SSE: one residual of 8 or two residuals of 4?",
        "The residual of 8 contributes 64. Two residuals of 4 contribute 16 + 16 = 32.",
      ),
      s(
        "The least-squares engine",
        "How does the best line get its numbers?",
        "Find average hours and average score. Use how they vary together and the spread of hours to calculate the slope. Then set the intercept so the fitted line goes through those two averages.",
        `${table(
          ["Calculation", "Live result"],
          [
            ["Average x, average y", live("means", "3.0, 60.0")],
            ["Σ(x − x̄)(y − ȳ)", live("xy", "49.0")],
            ["Σ(x − x̄)²", live("xx", "10.0")],
            ["m = shared movement / x spread", live("fit-slope", "4.90")],
            ["b = ȳ − mx̄", live("fit-intercept", "45.30")],
          ],
        )}<div class="formula">m = Σ(x − x̄)(y − ȳ) / Σ(x − x̄)²</div>`,
        "Fit the line, then edit one observation. The calculation receipt updates from those same rows.",
        "The slope is Σ(x−x̄)(y−ȳ)/Σ(x−x̄)². Bars mark averages. The intercept is ȳ−m x̄. These formulas solve the least-squares equations directly, without iterative training. If all x values are identical, the bottom is zero: we can estimate the mean there but cannot uniquely separate slope and intercept. When x varies, this fit gives the unique minimum within this line family.",
        "Why can’t we learn a slope if every student has exactly three study hours?",
        "There is no variation in x to compare. Many slope/intercept pairs give the same prediction at x = 3.",
      ),
      s(
        "The optimal line",
        "What does “best” promise?",
        "Best means the smallest training sum of squared errors among straight lines with an intercept. It does not mean the model found a cause or will predict every future student well.",
        `${table(
          ["Line", "SSE on these rows"],
          [
            ["Your current line", live("sse", "51.0")],
            ["Least-squares line", live("best-sse", "1.9")],
          ],
        )}<p>The fitted equation is <strong>${live("fit-equation", "ŷ = 45.30 + 4.90x")}</strong>.</p>`,
        "Press Fit line. Then nudge the slope in either direction: SSE cannot improve below the optimum.",
        "With an intercept, fitted residuals sum to zero up to rounding, and the line passes through the average x and y. Those are algebraic properties, not proof that assumptions or data quality are good. A tiny training SSE can coexist with bias, a curved true pattern or poor predictions outside training. Compare suitable new data and inspect what the residuals missed.",
        "Can another straight line have a smaller training SSE than this fit?",
        "Not when the same rows, squared-error objective and intercept are used and x varies. Another model family or objective is a different comparison.",
      ),
      s(
        "The model scorecard",
        "Better than what—and by how much?",
        "The baseline predicts the same average score for everybody. R² compares the line's squared errors with that baseline. Residual standard error estimates the remaining error spread in score units.",
        `${table(
          ["Quantity", "What it compares", "Live result"],
          [
            ["SST", "Actual scores vs average y", live("sst", "242.0")],
            ["SSE", "Actual scores vs fitted line", live("best-sse", "1.9")],
            [
              "R² = 1 − SSE/SST",
              "Reduction in training squared error",
              live("r2", "0.992"),
            ],
            [
              "RSE = √(SSE/(n − 2))",
              "Residual spread, score points",
              live("rse", "0.796"),
            ],
          ],
        )}`,
        "Edit a score into an outlier. Inspect the fit, the residuals and the scorecard together.",
        "For n rows, residual standard error uses √[SSE/(n−2)] because two coefficients were fitted. It needs positive residual degrees of freedom. Training R² with an intercept is between 0 and 1 when outcomes vary; held-out R² can be negative if the model is worse than its comparison baseline. Constant outcomes make this definition undefined. Mean-response intervals describe an estimated average; prediction intervals also include individual variation. Neither interval is drawn in this lab.",
        "Does an R² of 0.99 prove that study hours cause exam performance?",
        "No. It describes a strong fit on these observations. Confounding, selection and future prediction remain separate questions.",
      ),
      s(
        "Predict with care",
        "When is the line being asked to guess too far?",
        "Interpolation predicts inside the measured range of hours. Extrapolation predicts outside it. The line can return a number anywhere, but distant predictions may have little evidence behind them.",
        `${table(
          ["Prediction at x", live("query-x", "3.5")],
          [
            ["Your line", live("query-trial", "64.5")],
            ["Fitted line", live("query-fit", "62.45")],
          ],
        )}<p class="caution">${live("extrapolation", "3.5 is inside the observed range, 1–5 hours.")}</p><p><strong>What to report:</strong> slope with units, uncertainty, the observed range, residual diagnostics, validation error and the interval appropriate to the question.</p>`,
        "Move the prediction input beyond five hours. Notice when the visual marks extrapolation.",
        "The original x range is 1–5. A prediction at 4 is interpolation; at 20 it is distant extrapolation. Define prediction time, fit on training, inspect errors and influential points, compare a baseline on validation, then lock the procedure before final testing. This lab's line and scores use the five displayed rows and are training quantities. A fitted association does not establish causation.",
        "Is a prediction at x = 4 or x = 20 better supported by these original observations?",
        "x = 4. The original observed range is 1–5. x = 20 is a distant extrapolation.",
      ),
    ],
  },
  kmeans: {
    title: "K-Means Clustering",
    family: "Unsupervised learning · Clustering",
    accent: "green",
    intro:
      "Give a cloud of points a little structure. Then ask whether that structure makes sense.",
    prerequisite: "Coordinates, averages and distance",
    next: "Hierarchical Clustering",
    nextSlug: "hierarchical-clustering",
    summary:
      "Assign, average, repeat. Keep the same points while exploring what distance and initialization change.",
    stages: [
      s(
        "Start without labels",
        "What can we learn without a target?",
        "Each point describes one customer by age and monthly spending. We do not have a known correct group label. K-means makes groups around centres using the distance rule we choose.",
        table(
          ["Supervised learning", "This clustering task"],
          [
            ["Has an outcome to predict", "Has only measured features"],
            [
              "Checks predictions against labels",
              "Checks compactness, stability and usefulness",
            ],
          ],
        ),
        "Select a customer. Read their original measurements before thinking about groups.",
        "These 36 customers are synthetic teaching observations. Colours name proposed clusters, not verified types of customer. Feature choice, units, distance and K all define the grouping. Raw and standardized distance are available; the axes stay in original units, so a change in the distance rule does not secretly change the customers.",
        "Does a blue cluster imply a known customer category?",
        "No. Color identifies a proposed group. Interpretation requires domain knowledge and external evidence.",
      ),
      s(
        "Place the first centers",
        "Why does the starting point matter?",
        "Start with K centres. This lab chooses K different observed points using a reproducible seed. The seed controls the starting choice, not the customer data. Different starts can end in different groups.",
        `<div class="receipt-label">Initialization receipt</div><p>K = ${live("k", "3")} · seed = ${live("seed", "11")}<br>Method: random observations (Forgy).</p><p class="mini-note">A center is an average location. It need not remain on a customer.</p>`,
        "Try a new start, then step through the same data. Notice where the centers begin.",
        "This initializer uses a seeded shuffle of distinct observations. K-means++ is another method that favors separated starts using squared distances; it does not guarantee a globally best result. Random partitions are different again. Multiple restarts compare completed fits using the same data and scale. K is chosen before Lloyd's assignment/update iterations, not discovered automatically by them.",
        "Does changing the seed create different customers?",
        "No. It only changes initial centers. The points remain fixed.",
      ),
      s(
        "Assign to the nearest center",
        "Which center wins this point?",
        "Compare a point's distance to every current centre. Assign it to the nearest one. Finish assigning all points before moving any centres, so every assignment uses the same starting set of centres.",
        `<div class="receipt-label">Selected ${live("point-id", "P1")} · squared distances</div><div data-bind-html="distances">${table(
          ["Center", "Distance²"],
          [
            ["1", "Step once to assign"],
            ["2", "—"],
            ["3", "—"],
          ],
        )}</div><p class="mini-note">Squared distance and distance choose the same nearest center.</p>`,
        "Click Assign points. Select a customer near a group boundary and compare its distances to the centres.",
        "Straight-line distance is √Σ(x_j−centre_j)². The square root can be omitted when only comparing which distance is smallest. Equal distances follow a fixed lower-centre-number rule here. In standardized mode, calculations use transformed coordinates even though the axes show original units. Screen spacing alone is not the numerical distance rule.",
        "Do we move a center immediately after assigning one point?",
        "No. Assign every point using the same current centers, then update the centers as a separate phase.",
      ),
      s(
        "Recenter by averaging",
        "Why does the center move to the mean?",
        "For each group, average its members' coordinates. That mean becomes the new centre. For fixed membership, it gives the smallest total squared distance within that group.",
        `<div class="formula">new center = (mean x, mean y)</div><p>Phase: <strong>${live("phase", "Initialized")}</strong><br>Completed recentering rounds: ${live("iteration", "0")}</p>`,
        "The outlined group and hollow cross show a worked mean. Click Assign points if needed, then Move centers. Watch the star move while memberships stay fixed.",
        "The coordinate average minimizes squared Euclidean distances for fixed group members. That is why the mean and this objective belong together. Manhattan distance would use a different objective and centre rule. An empty group has no mean; this lab retains its previous centre and reports the empty group. Animated intermediate positions illustrate movement, not extra calculated clustering steps.",
        "Must the new center coincide with an observed customer?",
        "No. The average may lie between observations.",
      ),
      s(
        "Repeat until assignments settle",
        "When should the algorithm stop?",
        "Repeat two separate phases: assign points, then move centres. Stop when another assignment changes no memberships. Back and Next show saved steps. Run finishes the current sequence once.",
        `${table(
          ["Phase", "Held fixed", "Updated"],
          [
            ["Assign", "Centers", "Memberships"],
            ["Recenter", "Memberships", "Centers"],
          ],
        )}<p>Current WCSS: ${live("wcss", "—")} · ${live("convergence", "Not converged yet")}</p>`,
        "Run to convergence, then go Back twice. Your earlier snapshots remain inspectable.",
        "Each exact assignment or mean-update phase cannot increase the squared-distance objective. It can settle at a local solution, not the globally smallest WCSS. Scrolling changes the explanatory scene without restarting the run. Changing K, scale, scenario or seed starts a new experiment. Compare completed solutions and stability rather than treating iteration count as group usefulness.",
        "Can two runs converge to different answers on exactly the same data?",
        "Yes. Different initial centers can lead to different local minima.",
      ),
      s(
        "Measure within-cluster spread",
        "What is WCSS actually adding up?",
        "WCSS is the sum of each point's squared distance to its assigned centre. It measures how compact the groups are in the chosen input scale. A smaller value is better for that particular objective.",
        `<div class="formula">WCSS = Σᵢ ‖xᵢ − c(assigned i)‖²</div><p>Selected point contribution: <strong>${live("contribution", "—")}</strong><br>Total contribution: <strong>${live("wcss", "—")}</strong></p>`,
        "Select a point far from its center. Compare its contribution with a nearby point.",
        "WCSS is also called inertia. It depends on input units, scaling, number of rows and K. Do not compare raw-dollar WCSS with standardized WCSS as if they had the same units. The optimal objective cannot increase when K rises on fixed data and scale, but a limited restart procedure may miss those optima. Compactness alone does not establish useful or meaningful segments.",
        "Can we compare WCSS = 20 after standardization with WCSS = 500 in raw units?",
        "Not as evidence that one fit is better: the distance units and therefore the objective have changed.",
      ),
      s(
        "Look for an elbow",
        "How many groups earn their complexity?",
        "Compare several K values. See how much each added centre reduces WCSS. An elbow suggests smaller gains after that point. It is a clue to judge, not an automatic answer.",
        `<div class="receipt-label">A real computation on these points</div><p>The curve fits K = 1…6 with five fixed starts per K and retains the smallest WCSS found. Select a point on the curve to try that K.</p>`,
        "Compare the plotted K values. Choose one near a bend, then use the Lesson map to return to a grouping section and run its steps.",
        "The elbow curve is computed from the displayed data and scale. A clear elbow may not exist. Compare stability, silhouette and outside knowledge with the intended use. Silhouette compares closeness within a cluster with separation from another cluster, using the chosen metric. More groups also mean more interpretation and maintenance work; no score proves one true partition.",
        "If the curve bends smoothly with no obvious corner, is K-means broken?",
        "No. There may be no uniquely compelling K. State the ambiguity and use additional evidence.",
      ),
      s(
        "Choose what distance means",
        "Should a dollar count as much as a year?",
        "Dollar differences can be numerically much larger than age differences. Standardization measures each input relative to its own spread. It changes what similar means; it does not prove both features are equally important.",
        table(
          ["Metric choice", "What one unit means"],
          [
            ["Raw Euclidean", "One year and one dollar enter numerically"],
            ["Z-score Euclidean", "One standard deviation in each feature"],
          ],
        ),
        "Choose raw units or standardized units, then press Run. The same customers stay in place while the fitted groups change.",
        "A z-score is (value−mean)/SD. Standardization can be useful when relative variation should have comparable influence, but is not a universal requirement. Domain weights or common-unit raw distances may be better for the question. This exploratory lab uses all displayed rows to fit its scale; a predictive pipeline must fit scaling and centres inside training folds. Extreme values can affect the scaler too.",
        "Does standardizing prove that age and spending are equally important?",
        "No. It imposes a particular distance convention. Importance is a domain question, not a consequence of unit conversion.",
      ),
      s(
        "Find the limits",
        "When do neat circles tell the wrong story?",
        "K-means prefers compact groups around means. A curved group, very different densities or extreme values can make that description unhelpful. The algorithm can finish correctly and still answer the wrong practical question.",
        `<p><strong>Try two stress tests:</strong> curved moons and one unusually large spender.</p><p><strong>What to report:</strong> features, scaling, K, initialization, restarts, final WCSS, stability and why the segments are useful.</p>`,
        "Choose Curved moons or Add outlier, then run. Describe what the method missed.",
        "Means can be pulled by extreme values. Curved, connected shapes may be divided into several compact clusters. Density-based or hierarchical methods offer different descriptions, not universal replacements. A new customer can use the saved scale and nearest-centre rule. Refitting the whole model changes what the group labels mean, so keep that distinct from assignment to a frozen model.",
        "Does reaching “Converged” establish that the clusters are real?",
        "No. It only says this optimization procedure stopped changing assignments. Geometry, stability and domain meaning still need evaluation.",
      ),
    ],
  },
  "naive-bayes": {
    title: "Naive Bayes",
    family: "Supervised learning · Classification",
    accent: "red",
    intro:
      "Start with a belief. Collect clues. Show exactly how the evidence changes the answer.",
    prerequisite: "Fractions and conditional probability",
    next: "Evaluation Metrics",
    nextSlug: "evaluation-metrics",
    summary:
      "Follow one coherent email example from training counts to posterior, then examine what the simplifying assumption leaves out.",
    stages: [
      s(
        "Begin with labeled examples",
        "What does the model learn from?",
        "Each email has measured clues and a known spam label. The training example has 40 spam and 60 ordinary messages. Those class frequencies give the model a starting probability before reading a new message's clues.",
        table(
          ["Training class", "Emails", "Prior"],
          [
            ["Spam", "40", "0.40"],
            ["Not spam", "60", "0.60"],
          ],
        ),
        "Count the 40 spam and 60 ordinary training emails. Divide by 100 to check the two starting probabilities.",
        "A prior is P(class), the chance assigned before observing this message's clues. Here P(spam)=40/100=.4. Training labels can contain errors and class frequencies may differ from deployment, especially if sampling was artificially balanced. A prior needs a justified source rather than being assumed true everywhere.",
        "If every clue is ignored, what is P(spam) in this example?",
        "40 / 100 = 0.40. The absence of measured evidence leaves the prior unchanged.",
      ),
      s(
        "Separate features from the answer",
        "What can the filter know at prediction time?",
        "A word is an input clue. The spam label is the training answer, not an input available for a new email. For binary word features, 1 means present and 0 absent. Absent is different from ignored.",
        table(
          ["Message property", "Role"],
          [
            ["Contains “free”", "Input feature"],
            ["Contains “winner”", "Input feature"],
            ["Known spam label", "Training target only"],
          ],
        ),
        "Change “free” from present to absent, then to ignore. These are three different questions.",
        "Absent contributes the probability of not seeing the word within the class. Ignored means the clue is not observed for this calculation and contributes no factor. A full Bernoulli model normally includes both present and absent terms across its vocabulary. The lab allows partial evidence so you can build the calculation one clue at a time. Learn tokenization and vocabulary choices inside training too.",
        "Can “the user later marked this as spam” be a prediction-time feature?",
        "Not if that action happens after prediction. It would leak the outcome into the inputs.",
      ),
      s(
        "Protect the unseen examples",
        "How do we check learning honestly?",
        "Keep the final test separate. Use development validation to choose words, model variant and smoothing. The small count table here is training data, not a measured final-test score.",
        table(
          ["Partition", "Allowed role"],
          [
            ["Training fold", "Learn vocabulary and probabilities"],
            ["Validation fold", "Compare settings"],
            ["Final test", "Evaluate the locked procedure once"],
          ],
        ),
        "Inspect the split diagram. Only training information flows into the model.",
        "Refit text processing and likelihood estimates inside every training fold. A vocabulary chosen using all messages lets held-out inputs influence development. Use appropriate sender, thread or time splits when messages are related. A pictured 80/20 split is only an example. This lab's posterior is an arithmetic demonstration, not a tested spam filter's accuracy.",
        "Should the final test help decide the smoothing strength?",
        "No. That is a development choice. Choose it with validation or cross-validation, then evaluate once on the protected test.",
      ),
      s(
        "Choose a likelihood for the feature",
        "Why are there several kinds of Naive Bayes?",
        "The Naive Bayes family shares a probability recipe. Different variants use different input types: word presence, word counts, categories or continuous measurements. Match the variant to what the numbers mean.",
        table(
          ["Variant", "Feature representation"],
          [
            ["Bernoulli", "Present / absent word"],
            ["Multinomial", "Word occurrence counts"],
            ["Categorical", "One of several named levels"],
            ["Gaussian", "A continuous measurement"],
          ],
        ),
        "Choose a feature representation. Compare a present/absent bit with a word count or category, and explain what one displayed value means.",
        "Bernoulli models binary presence and absence. Multinomial uses feature counts, so three word occurrences differ from one. Categorical uses discrete feature levels. Gaussian fits a mean and variance for each continuous input within each class. The name alone does not turn a binary measurement into a continuous one. Check the representation and validation behavior.",
        "Is a word appearing three times identical to binary “present”?",
        "Not as a representation. A count feature distinguishes one occurrence from three; binary presence does not.",
      ),
      s(
        "Count within each class",
        "What does “given spam” mean?",
        "Given spam means look only at the spam emails. Free appears in 30 of 40 spam messages and 6 of 60 ordinary ones. These fractions describe the word within each class, not the class among messages with that word.",
        `${table(
          ["Clue", "Spam: count / 40", "Not spam: count / 60"],
          [
            ["free", "30 / 40", "6 / 60"],
            ["winner", "24 / 40", "3 / 60"],
            ["meeting", "2 / 40", "30 / 60"],
          ],
        )}<div class="formula">P(free | spam) ≠ P(spam | free)</div>`,
        "Compare the free bars for spam and ordinary mail. Set smoothing to zero to see 30/40 and 6/60, then increase it and check what changes.",
        "P(free|spam) divides by all spam messages. P(spam|free) divides by messages with free. Bayes' rule links them using class priors and evidence. For binary smoothing α, likelihood=(count+α)/(class count+2α), because there are two outcomes. The printed counts are raw; the live receipt uses your selected smoothing value.",
        "Why is 30/40 not already P(spam | free)?",
        "Its denominator includes all spam messages. We have conditioned on spam, not on the observed word.",
      ),
      s(
        "Name the naive assumption",
        "Why can we multiply the clues?",
        "The model assumes clues act independently once the class is known. This lets us multiply their probabilities. Real words may still be related within a class, so repeated clues can make the result overconfident.",
        `<div class="formula">P(clues | class) ≈ ∏ P(clue | class)</div><p>“Free” copied into a second feature is the same evidence twice. Toggle the duplicate to see confidence change without receiving a new fact.</p>`,
        "Duplicate the free feature. Watch its factor appear twice and both class scores change. Did the message provide any new information?",
        "Conditional independence is an assumption inside each class, not a claim that words are unrelated across the whole inbox. Copying a feature repeats evidence rather than creating new information. Its changed posterior shows what happens when the model multiplies redundant clues as if separate. Validate rankings and probability calibration; neither check proves the assumption.",
        "Does a higher posterior after copying a feature mean we learned more?",
        "No. We repeated information. The stronger posterior is an artifact of treating redundant features as independent.",
      ),
      s(
        "Turn scores into a posterior",
        "How does evidence become a probability?",
        "For each class, multiply its starting probability by its clue likelihoods. These give class scores. Divide each score by the total of all class scores so the resulting probabilities add to one.",
        `${table(
          ["Step", "Live result"],
          [
            ["Spam score", live("spam-score", "0.175737")],
            ["Not-spam score", live("ham-score", "0.004370")],
            ["P(spam | selected clues)", live("posterior", "97.6%")],
          ],
        )}<p class="mini-note">Smoothing α = ${live("alpha", "1")}. Ignored features contribute no evidence.</p>`,
        "Add “meeting” as present. Follow its likelihood factor through both scores before looking at the posterior.",
        "Bayes' rule is P(c|x)=P(c)P(x|c)/Σ_k P(k)P(x|k). Σ means add over classes. The largest raw class score gives the same label as the largest normalized probability, but probability displays need normalization. If all scores are zero, the result is undefined. These are model probabilities, not guaranteed calibrated real-world risks.",
        "Do class scores have to add to one before normalization?",
        "No. They become posterior probabilities only after division by their sum.",
      ),
      s(
        "A continuous clue needs a density",
        "What changes when the feature is a height?",
        "For a separate height example, group A has average 165 cm and SD 7; group B has average 180 cm and SD 8. Compare each fitted curve's density at the measured height. This is not the email dataset.",
        table(
          ["Illustrative plant group", "Mean", "SD", "Prior"],
          [
            ["A", "165 cm", "7 cm", "0.5"],
            ["B", "180 cm", "8 cm", "0.5"],
          ],
        ),
        "Move the plant height marker through the overlap. Read the two density heights and normalized class probability.",
        "Density is a curve height, not the probability of one exact continuous value. Probability comes from area over a range. Density units are inverse measurement units. Gaussian Naive Bayes combines class-specific densities and priors, all fitted from training. This separate height example uses equal class priors; it is not derived from email counts. Nearly constant features need a stated variance-stabilizing rule.",
        "Is the density at 170 cm the probability of a plant being exactly 170 cm tall?",
        "No. Probability is area over an interval. Density is a height used to compare relative support at that measurement.",
      ),
      s(
        "Avoid zeros and tiny-number trouble",
        "Why add smoothing and use logarithms?",
        "A zero likelihood wipes out a whole product. Smoothing gives unseen outcomes some probability. Logs turn products into sums, helping avoid numerical underflow. Smoothing changes the model; logs change the arithmetic used to calculate it.",
        `<div class="formula">log score = log prior + Σ log likelihood</div><p>“Unicorn” appeared 0 times in spam and once in ordinary mail. Try it with α = 0, then α = 1.</p>`,
        "Set unicorn to present and smoothing to zero. Increase α and inspect the repaired likelihood.",
        "For Bernoulli, adding α to both outcomes adds 2α to the denominator. For a multinomial vocabulary of V terms, the count denominator instead gains αV. Logs preserve order while avoiding a product becoming too tiny to represent. Stable normalization subtracts the largest log score before exponentiating. A zero likelihood has log −∞; all classes impossible remains undefined rather than invented.",
        "Does switching from products to log sums itself change the predicted class?",
        "No, apart from numerical precision. Log is monotonic. Smoothing can change the model, while logs change how its arithmetic is computed.",
      ),
      s(
        "Validate the whole recipe",
        "What happens in one cross-validation round?",
        "With five folds, train on four and validate on the fifth. Rotate that held-out group. Every scored row is predicted without training on it. Keep the final test outside this development loop.",
        `<div class="receipt-label">Five-fold development loop</div><p>Selected round: ${live("fold", "1")}. Blue folds fit the complete pipeline; the gold fold validates it. No invented accuracy score is attached to this diagram.</p>`,
        "Select each validation fold. Trace the held-out role as it moves across rounds.",
        "Cross-validation assesses a fitting procedure. Relearn vocabulary, feature selection and probability parameters in each training turn. Stratification can help class counts; groups or time address other structure. Searching many settings can overfit development scores, so a suitable outer evaluation or protected final test is still needed. Report the split design and uncertainty.",
        "May vocabulary selection run once on every fold before cross-validation?",
        "No. If it learns from the data, fit it inside each training fold to keep validation independent.",
      ),
      s(
        "Choose a decision, not just a class",
        "When should a message be flagged?",
        "A probability becomes an action after we choose a cutoff. A lower cutoff catches more spam but can flag more ordinary messages. Choose the tradeoff using validation and the consequences of each mistake.",
        `${table(
          ["Error", "Practical cost"],
          [
            ["False positive", "An ordinary email is hidden"],
            ["False negative", "Spam reaches the inbox"],
          ],
        )}<p>Current rule: flag if P(spam) ≥ ${live("threshold", "0.50")}.<br>Selected message: <strong>${live("decision", "Flag as spam")}</strong>.</p>`,
        "Move the threshold past the current posterior. The evidence stays the same; the action changes.",
        "Precision asks how many flagged messages are actually spam; recall asks how many actual spam messages were caught. Those rates need many labelled predictions, not one posterior. A cutoff based on costs also needs credible cost and probability assumptions. Capacity, delayed labels and later class-frequency changes can matter. Changing the cutoff does not refit word likelihoods.",
        "Does changing the threshold retrain the word likelihoods?",
        "No. It changes the action rule applied to the same estimated probabilities.",
      ),
      s(
        "Put the whole story together",
        "What should you remember when using it?",
        "Use available clues, protect evaluation data, choose the right likelihood type, fit counts and check the independence assumption. Then select and evaluate the decision rule. A confident probability is not the end of the evidence.",
        `<p><strong>Use it when:</strong> a fast, interpretable probability baseline suits the feature representation.</p><p><strong>Be careful when:</strong> evidence is strongly redundant, labels drift, rare categories dominate or probability calibration matters.</p><p><strong>What to report:</strong> variant, feature construction, smoothing, split design, decision threshold, held-out metrics, calibration and limitations.</p>`,
        "Ignore every clue, then add them one at a time. Explain each change before reading the result.",
        "Compare against useful baselines on suitable data. Watch for unseen values, changed class frequencies, redundant clues and preprocessing leakage. A simple calculation makes assumptions easier to inspect, but does not make them true. Distinguish training counts, validation choices and final evaluation, including calibration and decision consequences.",
        "What is the most important missing step after obtaining a very confident posterior?",
        "Evaluate the complete procedure on independent data, including calibration and the consequences of the chosen decision rule.",
      ),
    ],
  },
  "evaluation-metrics": {
    title: "Evaluation Metrics",
    family: "Model evaluation · Foundations",
    accent: "gold",
    intro:
      "A good-looking number is only useful when it answers the right question.",
    prerequisite: "Predictions and train / validation / test splitting",
    next: "Imbalanced Classification",
    nextSlug: "imbalanced-classification",
    summary:
      "Follow the same 1,000 fixed validation predictions from errors to thresholds, trade-offs and a defensible decision.",
    stages: [
      s(
        "Begin with the decision",
        "What happens when this model is wrong?",
        "A model can miss a positive case or raise a false alarm. These mistakes may have different costs. Define the decision and what matters before choosing a score.",
        table(
          ["Decision error", "Question to ask"],
          [
            ["False negative", "What is the cost of missing a case?"],
            [
              "False positive",
              "What is the cost and workload of an unnecessary alert?",
            ],
          ],
        ),
        "Inspect the two types of mistakes in the matrix before moving the threshold.",
        "A metric summarizes predictions for a defined target and sample. It does not choose the objective. The lab uses 1,000 fixed constructed validation scores, with 100 positives. These teach counts and tradeoffs; they are not evidence of a deployed screening product's performance. Define the population, prediction time, action, workload and error costs.",
        "Why can two applications prefer different thresholds for the same model?",
        "They may have different error costs, review capacity, prevalence or action constraints.",
      ),
      s(
        "Choose the denominator",
        "Whose success rate are we measuring?",
        "Accuracy looks at all cases. Precision looks only at alerts. Recall looks only at actual positives. Different bottom numbers answer different questions, so the same predictions can produce different percentages.",
        table(
          ["Metric", "Numerator / denominator"],
          [
            ["Accuracy", "(TP + TN) / all cases"],
            ["Precision", "TP / (TP + FP)"],
            ["Recall", "TP / (TP + FN)"],
            ["Specificity", "TN / (TN + FP)"],
            ["F1", "2TP / (2TP + FP + FN)"],
          ],
        ),
        "Choose Precision or Recall in the visual. The matrix highlights the cases in its denominator.",
        "TP and TN are correct positive and negative decisions; FP is a false alert and FN a missed positive. F1 combines precision and recall using their harmonic mean, ignoring true negatives. If no cases are alerted, precision divides by zero and is undefined. For numeric prediction, MAE averages absolute errors and RMSE takes √mean(error²). Both use outcome units; RMSE emphasizes large misses. Percentage errors such as MAPE can fail near zero outcomes.",
        "For residuals 1 and 3, what are MAE and RMSE?",
        "MAE = (1 + 3)/2 = 2. RMSE = √((1² + 3²)/2) = √5 ≈ 2.24. Larger misses receive more weight in RMSE.",
      ),
      s(
        "Worked example",
        "How can 89% accuracy hide so many false alerts?",
        "At cutoff .50, the example finds 80 of 100 positives and flags 90 of 900 negatives. That gives 170 alerts, with only 80 correct. Good overall accuracy can still hide many false alerts.",
        `${table(
          ["At the current threshold", "Calculation"],
          [
            [
              "Confusion counts",
              live("counts", "TP 80 · FN 20 · FP 90 · TN 810"),
            ],
            ["Accuracy", live("accuracy-receipt", "(80 + 810) / 1000 = 89.0%")],
            ["Precision", live("precision-receipt", "80 / 170 = 47.1%")],
            ["Recall", live("recall-receipt", "80 / 100 = 80.0%")],
          ],
        )}<p class="mini-note">The receipt follows the threshold. Reset restores the worked example.</p>`,
        "Select the false-positive cell to inspect an individual prediction that contributed to it.",
        "The counts are TP=80, FN=20, FP=90, TN=810. Precision=80/170≈47.1%; 90/170≈52.9% of alerts are false. Accuracy=890/1000=89%. Predicting every case negative gives 90% accuracy but zero recall. These fixed teaching counts do not include sampling or label uncertainty.",
        "Which denominator answers “how many of the alerts were right”?",
        "TP + FP, the total alerts. That gives precision, not recall.",
      ),
      s(
        "Separate ranking from decisions",
        "What does a threshold change?",
        "The fitted scores stay fixed. A cutoff turns them into yes/no decisions. ROC compares recall with false-positive rate across cutoffs. A precision–recall curve shows how well the positive predictions perform.",
        table(
          ["Question", "Useful view"],
          [
            ["Can scores rank positives above negatives?", "ROC curve and AUC"],
            [
              "How reliable are alerts as recall changes?",
              "Precision–recall curve",
            ],
            [
              "What happens at this one threshold?",
              "Confusion matrix and workload",
            ],
          ],
        ),
        "Compare ROC above with precision–recall below. Move the threshold and follow both operating points.",
        "ROC-AUC describes positive-versus-negative ranking, giving ties half credit. It is not accuracy at one cutoff or a calibration score. Precision depends on prevalence, the actual positive fraction. The curves and matrix here use the same fixed labelled scores. With no alerts, precision is undefined, so the PR operating point is omitted rather than invented. A strictly increasing score transformation preserves rankings but may change calibration.",
        "If every score is changed by a strictly increasing transformation, must the ranking change?",
        "No. Ranking can stay identical while the numerical probabilities and their calibration change.",
      ),
      s(
        "Interactive laboratory",
        "Where should the threshold sit?",
        "Try a cutoff, count the mistakes and translate them into consequences. Lowering it catches at least as many positives from fixed scores, but can add false alerts. There is no best cutoff for every application.",
        `<div data-interactive="metrics" class="receipt-label">A fixed validation experiment</div><p>Threshold ${live("threshold", "0.50")} → ${live("alerts", "170")} alerts.<br>Cost = FN × ${live("fn-cost", "20")} + FP × ${live("fp-cost", "1")} = <strong>${live("cost", "490")}</strong> illustrative cost units.</p>`,
        "Adjust threshold and error costs. Compare a candidate decision with the starting point.",
        "Scores equal to the cutoff count as positive here. Cost values are illustrative weights, not measured money or clinical costs. Changing a cost does not change the probabilities. Tune the decision using validation and explicitly stated consequences. A capacity limit such as 120 reviews is another possible constraint; compare it with the actual alert count.",
        "Does lowering the threshold improve the underlying probability estimates?",
        "No. It changes decisions, not the scores or their calibration.",
      ),
      s(
        "Assumptions and failure modes",
        "When is a metric answering the wrong question?",
        "A correctly calculated score can still describe the wrong sample. Check how cases were chosen, whether labels are reliable, and whether the evaluation resembles real use.",
        `<h3>Assumptions</h3><p>Independent held-out predictions; a deployment-relevant sample; valid labels; the same outcome and decision definitions.</p><h3>When the method fails</h3><p>Leakage, distribution shift, misleading averages, tiny subgroups, unequal error costs and metric shopping.</p>`,
        "Raise the threshold to 1.00. See the high-accuracy all-negative baseline and its zero recall.",
        "Changing class frequency can change precision even when sensitivity and specificity stay fixed in a hypothetical comparison. Real population changes may also change those rates. Repeated people need appropriate grouped evaluation; forecasting needs time-respecting evaluation. Report subgroup results with enough data and uncertainty rather than assuming an overall score describes everybody.",
        "Why can 99% accuracy be useless with 1% positives?",
        "An all-negative rule attains 99% accuracy while missing every positive case.",
      ),
      s(
        "Use an honest workflow",
        "When do we look at the final test?",
        "Choose the goal and main score first. Develop the model and cutoff using validation. Lock the whole pipeline, then evaluate once on a protected final test.",
        `<ol><li>Define the decision and costs.</li><li>Choose metrics and a relevant baseline.</li><li>Fit and tune within development data.</li><li>Lock preprocessing, model and threshold.</li><li>Report final test estimates with uncertainty.</li></ol>`,
        "Return to a threshold you can justify. State its trade-off before reading the scores.",
        "Preparation, selection, calibration and threshold choice are all part of the procedure. Learn them within appropriate development boundaries, including inside folds. Bootstrap uncertainty needs a resampling unit that matches the data structure. This interactive lesson remains a validation demonstration; moving a cutoff is not opening a final test. Retuning after viewing a final score makes it development feedback.",
        "What belongs on the final test set?",
        "One evaluation of the locked procedure. Threshold searches and feature choices belong in development.",
      ),
      s(
        "Report probability quality too",
        "Does “70%” behave like seventy out of a hundred?",
        "Calibration asks whether predicted probabilities match observed frequencies. Among similar cases scored near 70%, do about 70% actually turn out positive? Good ranking does not guarantee this agreement.",
        `${table(
          ["Probability score", "Same fixed predictions"],
          [
            ["Brier: mean (p − y)²", live("brier", "0.1371")],
            ["Log loss: −mean log P(actual class)", live("log-loss", "0.4530")],
          ],
        )}<p><strong>What to report:</strong> definition, threshold, prevalence, baseline, sample size, uncertainty, costs and relevant subgroup results.</p>`,
        "Compare each displayed bin’s average probability with its actual positive fraction. Inspect the bin counts before judging the difference.",
        "Brier score averages (probability−binary target)²; it reflects calibration and discrimination together. Log loss strongly penalizes confident mistakes. A reliability diagram compares average prediction with observed positive frequency in bins. This lab uses five fixed-width bins and shows their counts; small bins can be noisy. Even always predicting prevalence can be calibrated while ranking poorly. Fit recalibration using development predictions, not final-test answers.",
        "Does a low Brier score prove every subgroup is calibrated?",
        "No. It summarizes probability error overall. Inspect calibration, subgroup evidence and uncertainty separately.",
      ),
      s(
        "Check the reasoning",
        "Can you explain the result without hiding behind a score?",
        "Explain who was evaluated, what was predicted, what action followed, and what the mistakes meant. Use the checks below to support a clear decision rather than hiding behind one flattering number.",
        `<p>“At threshold ___, we catch ___ of the positives, send ___ alerts, and accept ___ false alarms under these stated costs.”</p><div data-knowledge-check>{{QUIZ}}</div>`,
        "Explain the precision denominator, the recall denominator and the reason for your threshold.",
        "State the target, sampling and split, fixed predictions, chosen score, baseline, validation decision and final evaluation with uncertainty. Explain complementary measures and which errors they reveal. Do not choose a metric after seeing which one makes a preferred model look best. Accuracy, F1 and AUC each leave out part of the decision story.",
        "What is missing from a report that says only “Accuracy = 89%”?",
        "The sample, prevalence, baseline, confusion counts or relevant error rates, threshold, decision costs, uncertainty and how the evaluation was kept independent.",
      ),
    ],
    questions: [
      [
        "Missed positive cases are especially costly. Which rate directly measures how many positives we catch?",
        ["Recall", "Specificity", "Precision"],
        0,
        "Recall divides true positives by all actual positives. Still report false positives and workload.",
      ],
      [
        "No predictions are positive. What is precision?",
        ["Undefined: its denominator is zero", "Always 0%", "Always 100%"],
        0,
        "TP + FP is zero. State the undefined value and show that there were no alerts.",
      ],
      [
        "What does Brier score evaluate?",
        ["Squared probability error", "Only true negatives", "Only ranking"],
        0,
        "It averages (p − y)² and reflects calibration and discrimination; it is not a pure calibration measure.",
      ],
      [
        "Where should a decision threshold be chosen?",
        [
          "Validation predictions, or predictions made while each row was left out of fitting",
          "Repeated final test searches",
          "Whichever set gives the highest score",
        ],
        0,
        "Keep the final test independent of model and decision-rule selection.",
      ],
      [
        "What should accompany a point estimate?",
        [
          "A relevant baseline and uncertainty",
          "Only extra decimal places",
          "Training accuracy alone",
        ],
        0,
        "Describe the sample, assumptions and uncertainty so the comparison can be interpreted.",
      ],
    ],
  },
};
