/* Author content here, then run npm run generate:pilots. HTML stays readable without JS. */
const table = (heads, rows) =>
  `<div class="table-wrap"><table><thead><tr>${heads.map((h) => `<th scope="col">${h}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((c, i) => (i ? `<td>${c}</td>` : `<th scope="row">${c}</th>`)).join("")}</tr>`).join("")}</tbody></table></div>`;
const live = (key, text) => `<span data-bind="${key}">${text}</span>`;
const s = (
  title,
  question,
  answer,
  receipt,
  experiment,
  why,
  check,
  solution,
) => ({ title, question, answer, receipt, experiment, why, check, solution });
export const pilots = {
  "simple-linear-regression": {
    title: "Simple Linear Regression",
    family: "Supervised learning · Regression",
    accent: "blue",
    intro:
      "One line. Five students. A surprisingly useful way to think about prediction.",
    prerequisite: "Means, coordinates and a little algebra",
    next: "Regression Diagnostics",
    nextSlug: "regression-diagnostics",
    summary:
      "Move a line, inspect its mistakes, then discover why least squares chooses one particular fit.",
    stages: [
      s(
        "The editable reality",
        "What is the line trying to explain?",
        "Each dot is one student. We use study hours <i>x</i> to predict a score <i>y</i>. The dots are observations; the line is our simplified description of their pattern.",
        `<div class="receipt-label">Our tiny dataset · edit a value</div>${table(
          ["Student", "Hours x", "Score y"],
          [50, 55, 61, 64, 70].map((y, i) => [
            "ABCDE"[i],
            `<input class="cell-input" aria-label="Student ${"ABCDE"[i]} hours" type="number" min="0" max="10" step="0.5" value="${i + 1}" data-point="${"ABCDE"[i]}" data-field="x">`,
            `<input class="cell-input" aria-label="Student ${"ABCDE"[i]} score" type="number" min="0" max="100" value="${y}" data-point="${"ABCDE"[i]}" data-field="y">`,
          ]),
        )}<p class="mini-note">Five observations illustrate the calculation. They cannot establish that studying caused a higher score.</p>`,
        "Change C’s score from 61 to 80. Which part of the pattern changed?",
        "A row is one observational unit; a feature is an input available at prediction time; a target is what we want to predict. Linear regression describes the conditional mean, E[y | x], as β₀ + β₁x. Real outcomes vary around that mean. Here all five rows are used for a transparent training example. For a predictive claim, keep independent observations for validation and a final test. A confounder, such as prior preparation, could influence both hours and scores.",
        "If two students study for three hours, must their scores match?",
        "No. The line estimates a mean response. Individual scores can differ because of other influences and random variation.",
      ),
      s(
        "Make your guess",
        "What do slope and intercept actually do?",
        "Slope tilts the line: it is the predicted change in score for one extra hour. Intercept moves the whole line up or down: it is the prediction at zero hours.",
        `<div class="formula">ŷ = b + mx</div>${table(
          ["Part", "Read it aloud"],
          [
            ["m = slope", "Score points per extra hour"],
            ["b = intercept", "Predicted score at zero hours"],
            ["ŷ = prediction", "Where the line sits at this x"],
          ],
        )}<p>Your current line: <strong>${live("equation", "ŷ = 40.0 + 7.0x")}</strong></p>`,
        "Change only the slope. Then change only the intercept. Watch which movement each controls.",
        "The hat in ŷ means an estimate, not the observed outcome y. A line is “linear” here because the unknown coefficients enter additively. The slope has outcome units divided by input units; the intercept has outcome units. An intercept may lie outside the observed x range, so its numerical meaning need not have a useful real-world interpretation. A negative slope is allowed. The displayed trial line is your choice; it is not yet the least-squares fit.",
        "With slope 7, what does two more hours change in the prediction?",
        "The prediction rises by 14 score points. This is a model-based association, not a guaranteed individual improvement.",
      ),
      s(
        "Measuring the mistakes",
        "How wrong is one prediction?",
        "A residual is actual minus predicted. Read vertically from the line to the dot, because we are predicting y at a fixed x. A dot above the line has a positive residual.",
        `<div class="receipt-label">Selected student ${live("student", "C")} · live calculation</div>${table(
          ["Step", "Value"],
          [
            ["Actual y", live("actual", "61.0")],
            ["Predicted ŷ", live("predicted", "61.0")],
            ["Residual y − ŷ", live("residual", "0.0")],
          ],
        )}<p class="mini-note">Select a dot, or use the student selector in the visual.</p>`,
        "Select two students on opposite sides of your line. Compare the residual signs.",
        "Residuals are observed training errors, eᵢ = yᵢ − ŷᵢ. They estimate the unobserved disturbances in the population model. Ordinary least squares measures vertical discrepancies, not the shortest perpendicular distance to the line. Perpendicular distances answer a different problem in which variation in both coordinates is treated symmetrically. A residual of −4 means the prediction was 4 points too high. A residual of +4 means it was 4 points too low.",
        "The actual score is 61 and the predicted score is 65. What is the residual?",
        "61 − 65 = −4. The model overpredicted by four points.",
      ),
      s(
        "A penalty that cannot cancel",
        "Why square the errors?",
        "Adding signed residuals can hide mistakes: +4 and −4 sum to zero. Squaring keeps both penalties positive and gives large misses extra weight.",
        `${table(["Residuals", "Signed sum", "Squared sum"], [["+4 and −4", "0", "16 + 16 = 32"]])}<p>Current SSE: <strong>${live("sse", "51.0")}</strong> score-points².<br>Current MAE: <strong>${live("mae", "2.6")}</strong> score points.</p>`,
        "Turn on squared-error tiles. Increase the slope and watch the largest misses dominate.",
        "SSE means sum of squared errors: Σ(yᵢ − ŷᵢ)². Squaring creates a smooth objective with a closed-form solution for a full-rank linear model. It also makes least squares sensitive to unusual large residuals. MAE, the mean absolute error, penalizes misses proportionally and can be more robust; minimizing it is a different fitting problem. The visual tiles use an area proportional to squared residual. They are an error-size cue, not a new x-coordinate measurement. SSE has squared outcome units; RMSE and RSE return to outcome units.",
        "Which contributes more to SSE: one residual of 8 or two residuals of 4?",
        "The residual of 8 contributes 64. Two residuals of 4 contribute 16 + 16 = 32.",
      ),
      s(
        "The least-squares engine",
        "How does the best line get its numbers?",
        "First find the average x and average y. Then measure how they vary together. Divide that shared movement by the spread in x to get the slope; choose the intercept so the line passes through the two averages.",
        `${table(
          ["Calculation", "Live result"],
          [
            ["Average x, average y", live("means", "3.0, 60.0")],
            ["Σ(x − x̄)(y − ȳ)", live("xy", "49.0")],
            ["Σ(x − x̄)²", live("xx", "10.0")],
            ["m = shared movement / x spread", live("fit-slope", "4.90")],
            ["b = ȳ − mx̄", live("fit-intercept", "45.30")],
          ],
        )}<div class="formula">m = Σ(x − x̄)(y − ȳ) / Σ(x − x̄)²</div>`,
        "Fit the line, then edit one observation. The calculation receipt updates from those same rows.",
        "Differentiating SSE with respect to b and m and setting both derivatives to zero gives the normal equations. Solving them yields the formula above and b = ȳ − mx̄. When x varies, this is the unique minimum for an intercept-and-slope fit. If every x is identical, the denominator is zero: slope and intercept cannot be identified separately. You can still estimate the mean at that observed x, but there is no unique regression slope. No iterative gradient descent is needed for this tiny model.",
        "Why can’t we learn a slope if every student has exactly three study hours?",
        "There is no variation in x to compare. Many slope/intercept pairs give the same prediction at x = 3.",
      ),
      s(
        "The optimal line",
        "What does “best” promise?",
        "It promises the smallest training SSE among all straight lines with an intercept. It does not promise the right causal story, reliable extrapolation, or the smallest error on future students.",
        `${table(
          ["Line", "SSE on these rows"],
          [
            ["Your current line", live("sse", "51.0")],
            ["Least-squares line", live("best-sse", "1.9")],
          ],
        )}<p>The fitted equation is <strong>${live("fit-equation", "ŷ = 45.30 + 4.90x")}</strong>.</p>`,
        "Press Fit line. Then nudge the slope in either direction: SSE cannot improve below the optimum.",
        "With an intercept, the fitted residuals sum to zero (up to numerical precision), and the fitted line passes through (x̄, ȳ). These are algebraic properties of least squares, not checks that the scientific assumptions hold. A very small training error can coexist with a biased dataset. Compare predictive performance on held-out data and inspect residual patterns. If the relationship curves, a straight-line family may simply be too restrictive.",
        "Can another straight line have a smaller training SSE than this fit?",
        "Not when the same rows, squared-error objective and intercept are used and x varies. Another model family or objective is a different comparison.",
      ),
      s(
        "The model scorecard",
        "Better than what—and by how much?",
        "Our baseline predicts the average score for everyone. R² compares the fitted line’s squared errors with that baseline. Residual standard error estimates the residual spread in score points.",
        `${table(
          ["Quantity", "What it compares", "Live result"],
          [
            ["SST", "Actual scores vs average y", live("sst", "242.0")],
            ["SSE", "Actual scores vs fitted line", live("best-sse", "1.9")],
            [
              "R² = 1 − SSE/SST",
              "Reduction in training squared error",
              live("r2", "0.992"),
            ],
            [
              "RSE = √(SSE/(n − 2))",
              "Residual spread, score points",
              live("rse", "0.796"),
            ],
          ],
        )}`,
        "Edit a score into an outlier. Inspect the fit, the residuals and the scorecard together.",
        "Two fitted coefficients consume two degrees of freedom, hence n − 2 in RSE. With an intercept, training R² lies between 0 and 1 when y varies. Held-out R² can be negative if the model is worse than the comparison baseline; when all y values are identical, this R² definition divides by zero and is undefined. Inspect residual-versus-fitted plots for curvature and changing spread; use leverage and Cook’s distance for influence. Independence comes from study design. Classical small-sample inference needs additional error assumptions. A confidence interval covers uncertainty in the estimated mean response; a prediction interval for a new individual is wider because it also includes individual variation. No interval is drawn here.",
        "Does an R² of 0.99 prove that study hours cause exam performance?",
        "No. It describes a strong fit on these observations. Confounding, selection and future prediction remain separate questions.",
      ),
      s(
        "Predict with care",
        "When is the line being asked to guess too far?",
        "Interpolation stays within the observed x range. Extrapolation goes outside it, where the pattern may change. The line can return a number anywhere; that does not make every number credible.",
        `${table(
          ["Prediction at x", live("query-x", "3.5")],
          [
            ["Your line", live("query-trial", "64.5")],
            ["Fitted line", live("query-fit", "62.45")],
          ],
        )}<p class="caution">${live("extrapolation", "3.5 is inside the observed range, 1–5 hours.")}</p><p><strong>What to report:</strong> slope with units, uncertainty, the observed range, residual diagnostics, validation error and the interval appropriate to the question.</p>`,
        "Move the prediction input beyond five hours. Notice when the visual marks extrapolation.",
        "Use this workflow: define the prediction time and outcome; split independent units; fit on training data; inspect residuals and influential observations; compare against a relevant baseline on validation data; lock the method; evaluate on the final test. Good prediction also requires the new population to resemble the data used for development. A coefficient is an adjusted association only relative to the variables in the model; causal claims need a defensible causal design. For this demonstration, the fitted line and all scorecard values use the five displayed rows, so they are training quantities.",
        "Is a prediction at x = 4 or x = 20 better supported by these original observations?",
        "x = 4. The original observed range is 1–5. x = 20 is a distant extrapolation.",
      ),
    ],
  },
  kmeans: {
    title: "K-Means Clustering",
    family: "Unsupervised learning · Clustering",
    accent: "green",
    intro:
      "Give a cloud of points a little structure. Then ask whether that structure makes sense.",
    prerequisite: "Coordinates, averages and distance",
    next: "Hierarchical Clustering",
    nextSlug: "hierarchical-clustering",
    summary:
      "Assign, average, repeat. Keep the same points while exploring what distance and initialization change.",
    stages: [
      s(
        "Start without labels",
        "What can we learn without a target?",
        "Each point is a customer described by age and monthly spending. There is no correct group label in this exercise. K-means proposes compact groups based on the distance we choose.",
        table(
          ["Supervised learning", "This clustering task"],
          [
            ["Has an outcome to predict", "Has only measured features"],
            [
              "Checks predictions against labels",
              "Checks compactness, stability and usefulness",
            ],
          ],
        ),
        "Select a customer. Read their original measurements before thinking about groups.",
        "Unsupervised does not mean assumption-free. The feature choice, units, distance and K encode what similarity means. A discovered cluster is an algorithmic grouping, not automatically a natural type of person. These 36 synthetic observations are a teaching dataset. Both raw-unit and z-score distance are available; the axes continue to show original units so you can see that changing the metric does not change the customers.",
        "Does a blue cluster imply a known customer category?",
        "No. Color identifies a proposed group. Interpretation requires domain knowledge and external evidence.",
      ),
      s(
        "Place the first centers",
        "Why does the starting point matter?",
        "K-means starts with K candidate centers. Our reproducible initializer chooses K distinct observations as centers. Different starts can lead to different final groupings.",
        `<div class="receipt-label">Initialization receipt</div><p>K = ${live("k", "3")} · seed = ${live("seed", "11")}<br>Method: random observations (Forgy).</p><p class="mini-note">A center is an average location. It need not remain on a customer.</p>`,
        "Try a new start, then step through the same data. Notice where the centers begin.",
        "We use a seeded shuffle so a seed produces the same distinct starting observations. K-means++ instead spreads seeds with a probability related to squared distance; it often improves initialization but does not guarantee the global optimum. Random partition initialization is yet another method. Do not confuse these methods. Multiple restarts compare complete fits under the same distance and dataset. K is an input, not something Lloyd’s iterations discover automatically.",
        "Does changing the seed create different customers?",
        "No. It only changes initial centers. The points remain fixed.",
      ),
      s(
        "Assign to the nearest center",
        "Which center wins this point?",
        "Measure the point’s distance to every center and choose the smallest. All assignments use the current centers, before any center moves.",
        `<div class="receipt-label">Selected ${live("point-id", "P1")} · squared distances</div><div data-bind-html="distances">${table(
          ["Center", "Distance²"],
          [
            ["1", "Step once to assign"],
            ["2", "—"],
            ["3", "—"],
          ],
        )}</div><p class="mini-note">Squared distance and distance choose the same nearest center.</p>`,
        "Press Next step to assign the points. Select a point near a boundary and inspect its distances.",
        "Euclidean distance is √Σⱼ(xⱼ − cⱼ)². Minimizing it is equivalent to minimizing its square, so the assignment calculation can omit the square root. The cluster colors follow these exact calculations. Equal distances are resolved consistently in favor of the lower center number. The display uses original units, but standardized mode measures distances in z-score coordinates. Visual closeness on a resized plot must not replace the numerical distance calculation.",
        "Do we move a center immediately after assigning one point?",
        "No. Assign every point using the same current centers, then update the centers as a separate phase.",
      ),
      s(
        "Recenter by averaging",
        "Why does the center move to the mean?",
        "For each group, average its members’ coordinates. That average is the location that minimizes their total squared distance while their memberships stay fixed.",
        `<div class="formula">new center = (mean x, mean y)</div><p>Phase: <strong>${live("phase", "Initialized")}</strong><br>Completed recentering rounds: ${live("iteration", "0")}</p>`,
        "After assignment, press Next step again. Watch the centers move while memberships stay fixed.",
        "Each coordinate minimizes a sum of squared deviations at its arithmetic mean. This is why the method is called K-means, and why squared Euclidean distance and the mean belong together. Replacing the distance with Manhattan distance would call for coordinate medians, a different objective. If a cluster has no members, its mean is undefined. This demonstration retains its previous center and reports the empty cluster; other implementations can reseed it. During a visual transition the committed calculation is shown, and intermediate positions are only a movement cue.",
        "Must the new center coincide with an observed customer?",
        "No. The average may lie between observations.",
      ),
      s(
        "Repeat until assignments settle",
        "When should the algorithm stop?",
        "Alternate assignment and recentering. Stop when a new assignment step changes no memberships. Back and Next let you inspect every saved step; Run completes this sequence once.",
        `${table(
          ["Phase", "Held fixed", "Updated"],
          [
            ["Assign", "Centers", "Memberships"],
            ["Recenter", "Memberships", "Centers"],
          ],
        )}<p>Current WCSS: ${live("wcss", "—")} · ${live("convergence", "Not converged yet")}</p>`,
        "Run to convergence, then go Back twice. Your earlier snapshots remain inspectable.",
        "Under the squared Euclidean objective, assignment and recentering cannot increase WCSS. That descent leads to a local solution; it does not guarantee the globally smallest WCSS. Scrolling to a different lesson stage does not rerun or reset the algorithm. Changing K, scaling, scenario or the initialization seed explicitly starts a new experiment. Compare solutions across starts and assess stability. Iteration counts alone are not evidence that the groups are useful.",
        "Can two runs converge to different answers on exactly the same data?",
        "Yes. Different initial centers can lead to different local minima.",
      ),
      s(
        "Measure within-cluster spread",
        "What is WCSS actually adding up?",
        "WCSS adds every point’s squared distance to its assigned center. It measures compactness in the chosen feature space. Smaller is better for this objective, with important limits.",
        `<div class="formula">WCSS = Σᵢ ‖xᵢ − c(assigned i)‖²</div><p>Selected point contribution: <strong>${live("contribution", "—")}</strong><br>Total contribution: <strong>${live("wcss", "—")}</strong></p>`,
        "Select a point far from its center. Compare its contribution with a nearby point.",
        "WCSS is also called inertia. It depends on feature units, scaling, the number of observations and K. A value from raw-dollar distance is not directly comparable with a z-score WCSS. For a fixed representation, the optimal objective cannot rise as K increases, because additional centers can reproduce an earlier solution. A finite multi-start heuristic need not find those optima. A low value alone does not establish meaningful, stable or fair segments.",
        "Can we compare WCSS = 20 after standardization with WCSS = 500 in raw units?",
        "Not as evidence that one fit is better: the distance units and therefore the objective have changed.",
      ),
      s(
        "Look for an elbow",
        "How many groups earn their complexity?",
        "Fit several values of K and inspect how much each extra center reduces WCSS. A bend is a clue that additional groups bring smaller gains. It is a judgment aid, not an automatic answer.",
        `<div class="receipt-label">A real computation on these points</div><p>The curve fits K = 1…6 with five fixed starts per K and retains the smallest WCSS found. Select a point on the curve to try that K.</p>`,
        "Switch the visual to the elbow curve. Choose a K near the bend and inspect its groups.",
        "The plot recomputes from the displayed scenario and chosen feature scaling; it is not a decorative pre-drawn curve. Multiple starts reduce initialization sensitivity. Sometimes no clear elbow exists, and real structure may be gradual or hierarchical. Use stability across resamples, silhouette analysis, external evidence and the intended decision alongside compactness. A silhouette compares within-cluster closeness with separation from other clusters; it still inherits the metric’s assumptions. More segments also carry a practical interpretation and maintenance cost.",
        "If the curve bends smoothly with no obvious corner, is K-means broken?",
        "No. There may be no uniquely compelling K. State the ambiguity and use additional evidence.",
      ),
      s(
        "Choose what distance means",
        "Should a dollar count as much as a year?",
        "In raw units, spending differences can dominate age differences because their numbers are larger. Standardization expresses each feature in its own standard-deviation units. That changes the question of similarity.",
        table(
          ["Metric choice", "What one unit means"],
          [
            ["Raw Euclidean", "One year and one dollar enter numerically"],
            ["Z-score Euclidean", "One standard deviation in each feature"],
          ],
        ),
        "Choose raw units or standardized units, then press Run. The same customers stay in place while the fitted groups change.",
        "A z-score is (x − training mean) / training standard deviation. Standardization is appropriate when relative variation across features should have comparable influence; it is not a universal rule. Domain weights may be preferable, and scaling cannot rescue meaningless features. If clustering is part of a predictive pipeline, fit its scaler and centers inside each training fold. For exploratory analysis here, all displayed observations define the scaler. Standardization is sensitive to outliers; robust scaling is another choice to justify.",
        "Does standardizing prove that age and spending are equally important?",
        "No. It imposes a particular distance convention. Importance is a domain question, not a consequence of unit conversion.",
      ),
      s(
        "Find the limits",
        "When do neat circles tell the wrong story?",
        "K-means favors compact groups around means. Curved shapes, very different densities and outliers can make those groups misleading. An algorithm can converge cleanly to an unhelpful description.",
        `<p><strong>Try two stress tests:</strong> curved moons and one unusually large spender.</p><p><strong>What to report:</strong> features, scaling, K, initialization, restarts, final WCSS, stability and why the segments are useful.</p>`,
        "Choose Curved moons or Add outlier, then run. Describe what the method missed.",
        "Means move toward extreme observations, which can consume a center or distort other groups. Non-convex shapes may be split across several compact regions even when a human sees one curved group. DBSCAN can represent density-connected shapes but needs meaningful density settings; hierarchical clustering answers a different family of questions. Neither is universally better. Consider the data geometry and deployment needs. A new observation can be assigned to a fitted center using the same trained feature transformation; refitting everything changes the segments.",
        "Does reaching “Converged” establish that the clusters are real?",
        "No. It only says this optimization procedure stopped changing assignments. Geometry, stability and domain meaning still need evaluation.",
      ),
    ],
  },
  "naive-bayes": {
    title: "Naive Bayes",
    family: "Supervised learning · Classification",
    accent: "red",
    intro:
      "Start with a belief. Collect clues. Show exactly how the evidence changes the answer.",
    prerequisite: "Fractions and conditional probability",
    next: "Evaluation Metrics",
    nextSlug: "evaluation-metrics",
    summary:
      "Follow one coherent email example from training counts to posterior, then examine what the simplifying assumption leaves out.",
    stages: [
      s(
        "Begin with labeled examples",
        "What does the model learn from?",
        "An email becomes a row of measured clues plus its known label. Our teaching training sample has 40 spam emails and 60 ordinary emails. The class proportions supply the starting beliefs.",
        table(
          ["Training class", "Emails", "Prior"],
          [
            ["Spam", "40", "0.40"],
            ["Not spam", "60", "0.60"],
          ],
        ),
        "Inspect the class counts. With all clues ignored, the visual returns to these priors.",
        "Supervised learning uses labels supplied by a defined process; labels may still contain mistakes. The training examples should resemble the messages the filter will encounter. A prior P(class) is a probability before the current message’s measured clues are considered. Here we estimate it from the training class frequency. If data were sampled with an artificial class ratio, that ratio may not match deployment and needs justified correction.",
        "If every clue is ignored, what is P(spam) in this example?",
        "40 / 100 = 0.40. The absence of measured evidence leaves the prior unchanged.",
      ),
      s(
        "Separate features from the answer",
        "What can the filter know at prediction time?",
        "The words are inputs. The spam label is the answer used for training, not a clue supplied when classifying a new email. For a binary feature, present means 1 and absent means 0.",
        table(
          ["Message property", "Role"],
          [
            ["Contains “free”", "Input feature"],
            ["Contains “winner”", "Input feature"],
            ["Known spam label", "Training target only"],
          ],
        ),
        "Change “free” from present to absent, then to ignore. These are three different questions.",
        "Absent is evidence: it contributes P(word absent | class). Ignored means the feature is not observed for this calculation and contributes no factor. A full Bernoulli model normally includes both the present and absent terms for all vocabulary features. This visual explicitly allows partial evidence so you can build the calculation one clue at a time. It never silently treats an absent word as an ignored one. Tokenization and vocabulary selection belong inside training data, just like fitting class probabilities.",
        "Can “the user later marked this as spam” be a prediction-time feature?",
        "Not if that action happens after prediction. It would leak the outcome into the inputs.",
      ),
      s(
        "Protect the unseen examples",
        "How do we check learning honestly?",
        "Keep a final test set sealed. Use cross-validation within the remaining development data to choose the variant, vocabulary and smoothing. The little count table in this lesson is training data only.",
        table(
          ["Partition", "Allowed role"],
          [
            ["Training fold", "Learn vocabulary and probabilities"],
            ["Validation fold", "Compare settings"],
            ["Final test", "Evaluate the locked procedure once"],
          ],
        ),
        "Inspect the split diagram. Only training information flows into the model.",
        "The entire text-processing pipeline must be refit in each training fold. Building a vocabulary or choosing words from all messages before validation lets held-out information affect development. Split by sender, thread or time when random rows would mix related messages or reveal the future. An illustrative 80/20 picture is not a universally optimal ratio; sufficient independent examples and a deployment-matched design matter more. The live posterior here is an arithmetic demonstration, not a measured test accuracy.",
        "Should the final test help decide the smoothing strength?",
        "No. That is a development choice. Choose it with validation or cross-validation, then evaluate once on the protected test.",
      ),
      s(
        "Choose a likelihood for the feature",
        "Why are there several kinds of Naive Bayes?",
        "The family shares one probability recipe. The feature representation decides what kind of likelihood belongs in that recipe: binary presence, counts, categories or continuous measurements.",
        table(
          ["Variant", "Feature representation"],
          [
            ["Bernoulli", "Present / absent word"],
            ["Multinomial", "Word occurrence counts"],
            ["Categorical", "One of several named levels"],
            ["Gaussian", "A continuous measurement"],
          ],
        ),
        "Choose a variant to inspect its representation. The email posterior lab remains explicitly Bernoulli.",
        "Multinomial Naive Bayes models feature counts with class-specific event probabilities; it does not use the same binary absence factors as Bernoulli. Categorical Naive Bayes models each feature’s discrete levels. Gaussian Naive Bayes fits a mean and variance for each continuous feature within each class. Match the likelihood to the measurement process and assess held-out behavior. Merely choosing a different name does not convert binary word counts into continuous observations.",
        "Is a word appearing three times identical to binary “present”?",
        "Not as a representation. A count feature distinguishes one occurrence from three; binary presence does not.",
      ),
      s(
        "Count within each class",
        "What does “given spam” mean?",
        "Restrict attention to the spam emails, then count the clue. “Free” appears in 30 of 40 spam messages and 6 of 60 ordinary messages. These likelihoods are different from P(spam | free).",
        `${table(
          ["Clue", "Spam: count / 40", "Not spam: count / 60"],
          [
            ["free", "30 / 40", "6 / 60"],
            ["winner", "24 / 40", "3 / 60"],
            ["meeting", "2 / 40", "30 / 60"],
          ],
        )}<div class="formula">P(free | spam) ≠ P(spam | free)</div>`,
        "Use only the “free” clue. Compare its two likelihoods with the final posterior.",
        "Conditioning changes the denominator. P(free | spam) divides by the number of spam messages, whereas P(spam | free) divides by the number of messages containing “free.” Bayes’ rule connects these quantities through the prior and normalizing evidence. With additive smoothing α, a binary likelihood is (count + α) / (class count + 2α). There are two outcomes, present and absent, hence 2α. The live receipt uses the selected α; the table above is the raw training count before smoothing.",
        "Why is 30/40 not already P(spam | free)?",
        "Its denominator includes all spam messages. We have conditioned on spam, not on the observed word.",
      ),
      s(
        "Name the naive assumption",
        "Why can we multiply the clues?",
        "The model treats the features as independent after the class is known. This makes fitting manageable. In real language, clues can remain related even within a class.",
        `<div class="formula">P(clues | class) ≈ ∏ P(clue | class)</div><p>“Free” copied into a second feature is the same evidence twice. Toggle the duplicate to see confidence change without receiving a new fact.</p>`,
        "Duplicate the “free” feature. Watch the model become more confident for the same underlying message.",
        "Conditional independence is not the claim that words are unrelated across the entire inbox. It is a factorization within each class. Correlated predictors can cause redundant evidence to be counted repeatedly; resulting probabilities may be overconfident even when classification rankings are useful. The duplicate feature is an explicit assumption stress test, not a recommended transformation. Validation and probability calibration can reveal practical consequences, but neither proves the assumption.",
        "Does a higher posterior after copying a feature mean we learned more?",
        "No. We repeated information. The stronger posterior is an artifact of treating redundant features as independent.",
      ),
      s(
        "Turn scores into a posterior",
        "How does evidence become a probability?",
        "Multiply each prior by that class’s clue likelihoods. Those are unnormalized scores. Divide the spam score by the sum of both scores to make probabilities that add to one.",
        `${table(
          ["Step", "Live result"],
          [
            ["Spam score", live("spam-score", "0.175737")],
            ["Not-spam score", live("ham-score", "0.004370")],
            ["P(spam | selected clues)", live("posterior", "97.6%")],
          ],
        )}<p class="mini-note">Smoothing α = ${live("alpha", "1")}. Ignored features contribute no evidence.</p>`,
        "Add “meeting” as present. Follow its likelihood factor through both scores before looking at the posterior.",
        "For classes c, Bayes gives P(c | x) = P(c)P(x | c) / ΣₖP(k)P(x | k). The denominator is shared across classes, so classification by the largest unnormalized score gives the same winner. Normalization is still necessary to display probabilities. These posteriors are conditional on the model and its estimated likelihoods; they are not guaranteed calibrated real-world risks. If every class assigns zero probability to the evidence, normalization is undefined. The visual reports this case rather than inventing a probability.",
        "Do class scores have to add to one before normalization?",
        "No. They become posterior probabilities only after division by their sum.",
      ),
      s(
        "A continuous clue needs a density",
        "What changes when the feature is a height?",
        "For a separate example, imagine two groups of plants. Group A has mean height 165 cm and standard deviation 7 cm; B has mean 180 cm and standard deviation 8 cm. Compare their fitted densities at the observed height.",
        table(
          ["Illustrative plant group", "Mean", "SD", "Prior"],
          [
            ["A", "165 cm", "7 cm", "0.5"],
            ["B", "180 cm", "8 cm", "0.5"],
          ],
        ),
        "Move the plant height marker through the overlap. Read the two density heights and normalized class probability.",
        "A continuous distribution assigns probability to an interval, not a single exact value. The curve’s height is a probability density, with inverse measurement units; it is not P(height equals exactly 170). Gaussian Naive Bayes multiplies class-conditional densities across features and normalizes class scores. Means, variances and class priors must be estimated from training data. Variance smoothing prevents numerical problems when a feature is nearly constant. This separate plant example assumes equal class priors and is not derived from the email counts.",
        "Is the density at 170 cm the probability of a plant being exactly 170 cm tall?",
        "No. Probability is area over an interval. Density is a height used to compare relative support at that measurement.",
      ),
      s(
        "Avoid zeros and tiny-number trouble",
        "Why add smoothing and use logarithms?",
        "An unseen word can give a class a zero likelihood, wiping out its entire product. Smoothing assigns some probability to unseen outcomes. Logs turn a long product into a sum without changing which class wins.",
        `<div class="formula">log score = log prior + Σ log likelihood</div><p>“Unicorn” appeared 0 times in spam and once in ordinary mail. Try it with α = 0, then α = 1.</p>`,
        "Set unicorn to present and smoothing to zero. Increase α and inspect the repaired likelihood.",
        "For Bernoulli features, α is added to both the present and absent counts, so the denominator gains 2α. In a multinomial word-count model, the denominator instead gains α times vocabulary size. Smoothing expresses a regularizing assumption and can alter probabilities; it is not merely a floating-point fix. Logs address underflow from multiplying many small numbers. Stable normalization subtracts the largest log score before exponentiation (the log-sum-exp idea). A zero likelihood has log probability −∞. Both classes being impossible is reported as undefined.",
        "Does switching from products to log sums itself change the predicted class?",
        "No, apart from numerical precision. Log is monotonic. Smoothing can change the model, while logs change how its arithmetic is computed.",
      ),
      s(
        "Validate the whole recipe",
        "What happens in one cross-validation round?",
        "Train on four folds and validate on the fifth. Rotate the held-out fold so each development example is assessed by a model that did not train on it. Keep the final test outside this loop.",
        `<div class="receipt-label">Five-fold development loop</div><p>Selected round: ${live("fold", "1")}. Blue folds fit the complete pipeline; the gold fold validates it. No invented accuracy score is attached to this diagram.</p>`,
        "Select each validation fold. Trace the held-out role as it moves across rounds.",
        "Cross-validation estimates the performance of a fitting procedure, not the quality of one fixed set of coefficients. Refit the vocabulary, any feature selection, and likelihood parameters inside each training fold. Choose an appropriate splitter: stratification can stabilize class counts, while grouped or time-ordered splits address dependence or chronology. Repeatedly searching many settings on the same validation estimates can overfit selection; nested CV or a protected final test addresses that final evaluation question. Report the resampling design and uncertainty, not only the best mean.",
        "May vocabulary selection run once on every fold before cross-validation?",
        "No. If it learns from the data, fit it inside each training fold to keep validation independent.",
      ),
      s(
        "Choose a decision, not just a class",
        "When should a message be flagged?",
        "A posterior becomes an action only after choosing a threshold. Lower thresholds catch more spam but may flag more legitimate mail. Choose the trade-off on validation data using the consequences of each error.",
        `${table(
          ["Error", "Practical cost"],
          [
            ["False positive", "An ordinary email is hidden"],
            ["False negative", "Spam reaches the inbox"],
          ],
        )}<p>Current rule: flag if P(spam) ≥ ${live("threshold", "0.50")}.<br>Selected message: <strong>${live("decision", "Flag as spam")}</strong>.</p>`,
        "Move the threshold past the current posterior. The evidence stays the same; the action changes.",
        "Precision asks how many flagged messages really are spam; recall asks how many spam messages were caught. Those population metrics require many labeled held-out predictions, not one posterior. If probabilities are calibrated and false-positive and false-negative costs are known, a simple two-action decision threshold can be derived from those costs. Real systems also have review capacity, delayed labels and distribution shift. Evaluate calibration separately from ranking, and lock the decision rule before final testing.",
        "Does changing the threshold retrain the word likelihoods?",
        "No. It changes the action rule applied to the same estimated probabilities.",
      ),
      s(
        "Put the whole story together",
        "What should you remember when using it?",
        "Choose available features, protect evaluation data, match the likelihood, fit counts, inspect the assumption, then choose and validate a decision rule. Keep the arithmetic simple and the claims proportionate.",
        `<p><strong>Use it when:</strong> a fast, interpretable probability baseline suits the feature representation.</p><p><strong>Be careful when:</strong> evidence is strongly redundant, labels drift, rare categories dominate or probability calibration matters.</p><p><strong>What to report:</strong> variant, feature construction, smoothing, split design, decision threshold, held-out metrics, calibration and limitations.</p>`,
        "Ignore every clue, then add them one at a time. Explain each change before reading the result.",
        "Naive Bayes is often efficient to fit and predict, especially for sparse text representations. Its usefulness should be demonstrated relative to relevant baselines. Simplicity helps expose the model’s assumptions but does not make them true. A comprehensive report distinguishes training counts, validation choices and final test evidence. Check for rare or unseen feature values, class-prior shift, redundant evidence and preprocessing leakage. Return to the Evaluation Metrics lesson to connect message-level probabilities to confusion counts, workload and population-level performance.",
        "What is the most important missing step after obtaining a very confident posterior?",
        "Evaluate the complete procedure on independent data, including calibration and the consequences of the chosen decision rule.",
      ),
    ],
  },
  "evaluation-metrics": {
    title: "Evaluation Metrics",
    family: "Model evaluation · Foundations",
    accent: "gold",
    intro:
      "A good-looking number is only useful when it answers the right question.",
    prerequisite: "Predictions and train / validation / test splitting",
    next: "Imbalanced Classification",
    nextSlug: "imbalanced-classification",
    summary:
      "Follow the same 1,000 fixed validation predictions from errors to thresholds, trade-offs and a defensible decision.",
    stages: [
      s(
        "Begin with the decision",
        "What happens when this model is wrong?",
        "Imagine a screening model. Missing a positive case and raising a false alarm have different consequences. Choose what matters before choosing the score that summarizes it.",
        table(
          ["Decision error", "Question to ask"],
          [
            ["False negative", "What is the cost of missing a case?"],
            [
              "False positive",
              "What is the cost and workload of an unnecessary alert?",
            ],
          ],
        ),
        "Inspect the two types of mistakes in the matrix before moving the threshold.",
        "A metric is a summary of predictions under a particular outcome definition and evaluation sample. It does not choose the application’s objective for you. Define the population, prediction time, available action, acceptable workload and cost of error. This lesson uses 1,000 fixed illustrative validation scores, of which 100 are positive. They are a constructed teaching dataset, not the performance of a medical product. No clinical decision should be inferred from the example.",
        "Why can two applications prefer different thresholds for the same model?",
        "They may have different error costs, review capacity, prevalence or action constraints.",
      ),
      s(
        "Choose the denominator",
        "Whose success rate are we measuring?",
        "Accuracy looks at everyone. Precision looks only at alerts. Recall looks only at actual positives. The denominator changes the question, so the same predictions can produce very different percentages.",
        table(
          ["Metric", "Numerator / denominator"],
          [
            ["Accuracy", "(TP + TN) / all cases"],
            ["Precision", "TP / (TP + FP)"],
            ["Recall", "TP / (TP + FN)"],
            ["Specificity", "TN / (TN + FP)"],
            ["F1", "2TP / (2TP + FP + FN)"],
          ],
        ),
        "Choose Precision or Recall in the visual. The matrix highlights the cases in its denominator.",
        "A true positive is a positive case correctly alerted; a true negative is a negative case correctly left unflagged. F1 is the harmonic mean of precision and recall when defined. It ignores true negatives and does not encode every practical cost. If no cases are predicted positive, precision has denominator zero and is undefined; showing 0% would conceal that distinction. Regression uses different quantities: MAE = mean |y − ŷ| and RMSE = √mean(y − ŷ)². Both are in outcome units; RMSE emphasizes larger misses. MAPE can fail near zero outcomes.",
        "For residuals 1 and 3, what are MAE and RMSE?",
        "MAE = (1 + 3)/2 = 2. RMSE = √((1² + 3²)/2) = √5 ≈ 2.24. Larger misses receive more weight in RMSE.",
      ),
      s(
        "Worked example",
        "How can 89% accuracy hide so many false alerts?",
        "At threshold 0.50, our example finds 80 of 100 positive cases and flags 90 of 900 negative cases. There are 170 alerts, but only 80 are correct.",
        `${table(
          ["At the current threshold", "Calculation"],
          [
            [
              "Confusion counts",
              live("counts", "TP 80 · FN 20 · FP 90 · TN 810"),
            ],
            ["Accuracy", live("accuracy-receipt", "(80 + 810) / 1000 = 89.0%")],
            ["Precision", live("precision-receipt", "80 / 170 = 47.1%")],
            ["Recall", live("recall-receipt", "80 / 100 = 80.0%")],
          ],
        )}<p class="mini-note">The receipt follows the threshold. Reset restores the worked example.</p>`,
        "Select the false-positive cell to inspect an individual prediction that contributed to it.",
        "The counts reconcile: TP + FN = 100 positives, FP + TN = 900 negatives, and all four cells total 1,000. Precision is 80/170 ≈ 47.1%, so 90/170 ≈ 52.9% of alerts are false. Accuracy is 890/1,000 = 89%, yet predicting every case negative would achieve 90% accuracy and zero recall. That baseline illustrates why accuracy alone is not enough. None of these percentages captures uncertainty from sampling or label error.",
        "Which denominator answers “how many of the alerts were right”?",
        "TP + FP, the total alerts. That gives precision, not recall.",
      ),
      s(
        "Separate ranking from decisions",
        "What does a threshold change?",
        "The model’s scores stay fixed. A threshold converts them into yes/no decisions. A ROC curve compares recall with false-positive rate across thresholds; a precision–recall curve focuses on positive predictions.",
        table(
          ["Question", "Useful view"],
          [
            ["Can scores rank positives above negatives?", "ROC curve and AUC"],
            [
              "How reliable are alerts as recall changes?",
              "Precision–recall curve",
            ],
            [
              "What happens at this one threshold?",
              "Confusion matrix and workload",
            ],
          ],
        ),
        "Compare ROC above with precision–recall below. Move the threshold and follow both operating points.",
        "ROC-AUC is the probability that a randomly chosen positive ranks above a randomly chosen negative, counting ties appropriately. It summarizes all operating regions, some of which may be irrelevant to the actual decision. Precision depends on prevalence, so PR curves help reveal the burden of false positives in rare-class problems. Neither ranking metric establishes calibration. These curves are calculated from the same fixed labeled scores as the matrix, at every distinct score threshold. With zero alerts, precision is undefined; the PR operating point is omitted rather than fabricated.",
        "If every score is changed by a strictly increasing transformation, must the ranking change?",
        "No. Ranking can stay identical while the numerical probabilities and their calibration change.",
      ),
      s(
        "Interactive laboratory",
        "Where should the threshold sit?",
        "Try a threshold, count each type of error, and translate the errors into consequences. A low threshold catches more positive cases but usually creates more alerts. There is no universally best cutoff.",
        `<div data-interactive="metrics" class="receipt-label">A fixed validation experiment</div><p>Threshold ${live("threshold", "0.50")} → ${live("alerts", "170")} alerts.<br>Cost = FN × ${live("fn-cost", "20")} + FP × ${live("fp-cost", "1")} = <strong>${live("cost", "490")}</strong> illustrative cost units.</p>`,
        "Adjust threshold and error costs. Compare a candidate decision with the starting point.",
        "Threshold ≥ means scores exactly on the cutoff are classified positive. The cost values are illustrative weights, not monetary or clinical estimates. They turn an explicitly stated preference into a count-based comparison; changing costs does not alter model predictions. Tune on validation data or out-of-fold predictions. Choose a rule before inspecting final test performance. A capacity constraint, such as no more than 120 reviews, may matter in addition to cost. The visual reports actual alert count, so you can inspect that constraint directly.",
        "Does lowering the threshold improve the underlying probability estimates?",
        "No. It changes decisions, not the scores or their calibration.",
      ),
      s(
        "Assumptions and failure modes",
        "When is a metric answering the wrong question?",
        "A precise calculation can still describe an unrepresentative sample. Check where the data came from, whether labels are trustworthy and whether the split matches how the model will be used.",
        `<h3>Assumptions</h3><p>Independent held-out predictions; a deployment-relevant sample; valid labels; the same outcome and decision definitions.</p><h3>When the method fails</h3><p>Leakage, distribution shift, misleading averages, tiny subgroups, unequal error costs and metric shopping.</p>`,
        "Raise the threshold to 1.00. See the high-accuracy all-negative baseline and its zero recall.",
        "Sensitivity and specificity may remain stable under a pure prior-probability shift, but precision changes with prevalence. If positive prevalence falls, false positives can dominate alerts even at a modest false-positive rate. Real distribution shifts can also change the class-conditional score distributions, so do not assume only prevalence changed. Report relevant subgroup performance with uncertainty rather than hiding it in an aggregate. Repeated patients require grouped evaluation; forecasts require time-respecting evaluation.",
        "Why can 99% accuracy be useless with 1% positives?",
        "An all-negative rule attains 99% accuracy while missing every positive case.",
      ),
      s(
        "Use an honest workflow",
        "When do we look at the final test?",
        "Define the goal and primary metric first. Develop and choose thresholds with validation data. Lock the full pipeline. Only then evaluate once on the protected test set.",
        `<ol><li>Define the decision and costs.</li><li>Choose metrics and a relevant baseline.</li><li>Fit and tune within development data.</li><li>Lock preprocessing, model and threshold.</li><li>Report final test estimates with uncertainty.</li></ol>`,
        "Return to a threshold you can justify. State its trade-off before reading the scores.",
        "The pipeline includes imputation, scaling, feature selection, calibration and threshold selection—not just the final estimator. Cross-validation must repeat every learned step inside each training fold. Bootstrap intervals can describe sampling variability when their resampling unit matches independence; cluster or temporal dependence needs an appropriate resampling design. A final test is not a resource to repeatedly inspect and then retune. Our interactive scores remain validation examples throughout; this lesson does not pretend that trying a threshold constitutes a final test.",
        "What belongs on the final test set?",
        "One evaluation of the locked procedure. Threshold searches and feature choices belong in development.",
      ),
      s(
        "Report probability quality too",
        "Does “70%” behave like seventy out of a hundred?",
        "Calibration compares predicted risks with observed frequencies. Brier score and log loss evaluate probability predictions. A good ranking does not guarantee honest probabilities.",
        `${table(
          ["Probability score", "Same fixed predictions"],
          [
            ["Brier: mean (p − y)²", live("brier", "0.1371")],
            ["Log loss: −mean log P(actual class)", live("log-loss", "0.4530")],
          ],
        )}<p><strong>What to report:</strong> definition, threshold, prevalence, baseline, sample size, uncertainty, costs and relevant subgroup results.</p>`,
        "Open the calibration view. Compare each bin’s average prediction with its observed positive fraction.",
        "Brier score is sensitive to both calibration and discrimination; it is not a pure measure of calibration. Log loss strongly penalizes confident mistakes. A reliability diagram bins predictions and compares mean predicted probability with observed frequency, but small bins are noisy and bin choices matter. The visual uses five fixed-width bins and shows their counts. A perfectly calibrated forecast can still discriminate poorly, such as always predicting the population prevalence. Recalibration is a learned transformation: fit it using development data, not the final test.",
        "Does a low Brier score prove every subgroup is calibrated?",
        "No. It summarizes probability error overall. Inspect calibration, subgroup evidence and uncertainty separately.",
      ),
      s(
        "Check the reasoning",
        "Can you explain the result without hiding behind a score?",
        "A defensible evaluation connects the population, predictions, decision and consequences. Practice the five checks below, then explain your chosen threshold in a sentence.",
        `<p>“At threshold ___, we catch ___ of the positives, send ___ alerts, and accept ___ false alarms under these stated costs.”</p><div data-knowledge-check>{{QUIZ}}</div>`,
        "Explain the precision denominator, the recall denominator and the reason for your threshold.",
        "Keep the full path visible: trustworthy labels and split → fixed predictions → a prespecified metric and baseline → a validation choice → one final evaluation with uncertainty. Use the simplest quantity that answers the decision question while reporting enough complementary evidence to expose its blind spots. Neither accuracy nor F1 nor AUC can replace that chain of reasoning. Do not select whichever score happens to flatter a preferred model after seeing the results.",
        "What is missing from a report that says only “Accuracy = 89%”?",
        "The sample, prevalence, baseline, confusion counts or relevant error rates, threshold, decision costs, uncertainty and how the evaluation was kept independent.",
      ),
    ],
    questions: [
      [
        "Missed positive cases are especially costly. Which rate directly measures how many positives we catch?",
        ["Recall", "Specificity", "Precision"],
        0,
        "Recall divides true positives by all actual positives. Still report false positives and workload.",
      ],
      [
        "No predictions are positive. What is precision?",
        ["Undefined: its denominator is zero", "Always 0%", "Always 100%"],
        0,
        "TP + FP is zero. State the undefined value and show that there were no alerts.",
      ],
      [
        "What does Brier score evaluate?",
        ["Squared probability error", "Only true negatives", "Only ranking"],
        0,
        "It averages (p − y)² and reflects calibration and discrimination; it is not a pure calibration measure.",
      ],
      [
        "Where should a decision threshold be chosen?",
        [
          "Validation or out-of-fold predictions",
          "Repeated final test searches",
          "Whichever set gives the highest score",
        ],
        0,
        "Keep the final test independent of model and decision-rule selection.",
      ],
      [
        "What should accompany a point estimate?",
        [
          "A relevant baseline and uncertainty",
          "Only extra decimal places",
          "Training accuracy alone",
        ],
        0,
        "Describe the sample, assumptions and uncertainty so the comparison can be interpreted.",
      ],
    ],
  },
};
