// Instructions describe the experiment available in this exact reading section.
export const spatialPrompts = {
  "multiple-linear-regression": [
    "Rotate the data space. Select a blue observation and follow its vertical residual down to the green prediction plane.",
    "Change x₁, then x₂. Follow each signed contribution into the total; a negative contribution lowers the prediction.",
    "Tilt β₁ while leaving β₂ alone. Compare the plane, the residual threads, and training MSE on the same data.",
    "Try a poor slope, then choose “Find the least-squares plane”. Check that the training error falls while the observations stay fixed.",
    "Move x₁ along the green line while keeping x₂ fixed. The rise for a one-unit move is β₁. Then change the held value of x₂.",
    "Choose a negative input and follow the running total. Add the intercept and both products by hand before checking the last column.",
    "Compare the raw cloud with the residual cloud after removing x₂. These are the same observations; the adjusted slope can be very different.",
    "Include and remove the seeded noise predictor. Compare training R² with adjusted R², then draw another sample to see a chance result change.",
    "Increase outcome noise and watch the coefficient intervals widen. Read the dot as the estimate and the line as its model-based uncertainty.",
  ],
  "regression-trees": [
    "Select a dot. Read its numerical outcome, then keep that observation in mind as the following sections construct predictions.",
    "Count the training, validation and sealed test observations. Only the training outcomes may determine a split or a leaf mean.",
    "Move the constant prediction above and below the green mean. Follow the vertical gaps and compare your MSE with the best constant MSE.",
    "Slide the candidate midpoint. The two horizontal predictions are the means on either side; observations equal to a threshold go left.",
    "Keep a candidate cut fixed. Compare its child sample sizes, residual spreads and weighted impurity with the original parent.",
    "Move through candidate midpoints, then change the feature being tested. Compare the gold candidate with the green minimum of this feature’s cost curve.",
    "Reveal one more split level. Notice how a child’s cut stops at the edge of its own region.",
    "Move the query in either input. Follow the gold region above and the same gold branching route below to its leaf prediction.",
    "Increase maximum depth. Compare the training and validation curves; a better training fit need not improve held-out error.",
    "Change the minimum leaf size on the same sample. Inspect which spatial cuts and branches are no longer allowed.",
    "Raise α to remove branches from one fixed grown tree. Compare retained leaves, training risk and validation error. This is post-pruning.",
    "Hold x₂ fixed and compare the line-model slice with the tree’s steps. The background observations retain their own x₂ values.",
    "Change one growth setting at a time. Trace the same query before drawing a new dataset.",
    "Select a row and follow its vertical residual. Its prediction uses both inputs, even though this outcome plot shows x₁ on the horizontal axis.",
    "Perturb one training outcome. Compare the before-and-after partitions and the prediction at the same query.",
    "Trace a query from its location to a leaf. Explain the cut, the branch direction, the leaf sample size and its mean before checking the receipt.",
  ],
  "classification-trees": [
    "Inspect a point in the two-input space. Blue dots and red crossed dots distinguish the two target classes.",
    "Inspect the three sample groups. Test outcomes remain sealed while thresholds and leaf values are learned from training data.",
    "Count the two classes in the root. Before any split, every query would receive this same class-1 fraction.",
    "Move the toy class proportion from 0 to 1. Compare a pure node with a half-and-half node on the Gini curve.",
    "Scrub legal midpoint thresholds and switch the candidate feature. Compare the spatial cut with the minimum of the impurity curve.",
    "Compare the class mixtures in the two children. Weight their impurities by their sample sizes before subtracting from the parent.",
    "Reveal another split level. The new question applies only inside the parent’s rectangle.",
    "Move a query across a cut. Follow the gold rectangle to its leaf and notice why axis-aligned splits make rectangular regions.",
    "Raise the post-pruning penalty. The experiment starts from a fixed depth-5 tree, so it removes existing branches rather than stopping early.",
    "Compare training and validation error across maximum depths. Use held-out development evidence to choose complexity.",
    "Move the query across a threshold. Follow the yes/left or no/right route and verify the resulting leaf fraction.",
    "Read the validation points inside each confusion-matrix cell. Identify false positives and false negatives before comparing the counts.",
    "Trace a query and reconcile its path, leaf sample size and predicted class fraction. A leaf fraction is not a guarantee of correctness.",
    "Change depth or minimum leaf size while keeping the sample fixed. Inspect how the decision regions change.",
    "Move one training input and compare the resulting partitions. A small data change can alter a greedy tree.",
  ],
  "random-forest": [
    "Compare individual spatial partitions and move one training input. Check how the single trees and the all-tree prediction respond.",
    "Choose a tree and a training row. A square shows how many times that original row appeared in the bootstrap sample; zero means it was omitted.",
    "Follow the individual tree fractions and their running mean. Increase the tree count and recompute the same query’s aggregate.",
    "Compare two trees’ predictions on the same validation observations. Points near the diagonal indicate agreement; gold rings identify shared mistakes.",
    "Select a training row and inspect its voters. Crossed-out trees sampled that row, so they must not contribute to its out-of-bag prediction.",
    "Move one training input. Inspect the aggregate prediction field and gold-ringed validation mistakes; more trees do not guarantee correct predictions.",
    "Increase the number of trees and compare the measured validation-error curve. It need not improve after every added tree.",
    "Inspect the forest prediction in the original input space. Report the sample split, tree settings, aggregation rule and held-out error together.",
    "Choose a row and identify eligible voters before reading its OOB fraction. If no tree omitted it, the estimate is unavailable.",
  ],
  "neural-networks": [
    "Inspect the initial decision field, then train 20 updates. The examples stay fixed while the network reshapes its prediction boundary.",
    "Move x₁ and x₂. Follow the coordinate guides to one input point; its label is a separate target, not another input coordinate.",
    "Follow the three disjoint sample groups. Preprocessing and weight updates learn from training data; validation measures choices and test stays sealed.",
    "Change an input or the first weight. Follow the two products and bias into the weighted sum, then through the activation curve.",
    "Change the first connection weight. Only unit 1’s input response changes directly; compare all three responses at the same gold query.",
    "Choose an activation and compare its bend with the decision boundary below. Changing activation starts a fresh run.",
    "Follow the same gold point through all three hidden-response maps and into the combined output. Read the computed values in the receipt.",
    "Change the inspected true label while retaining the same prediction. Follow the point on the corresponding cross-entropy curve.",
    "Inspect the measured loss surface and gradient components. The downhill arrow is opposite the gradient; computing it alone has not updated weights.",
    "Choose a learning rate, predict the change in loss, then take one two-weight step. Rewind to recover the exact previous parameters.",
    "Step through forward, loss, gradients and update. Verify that weights change only at update, then rewind and replay.",
    "Train another batch of updates. Compare training loss with validation loss and the best stored validation step.",
    "Change activation to restart the run, or change learning rate for the next updates. Observe the measured development curves.",
    "Inspect the validation confusion matrix. This experiment keeps final-test labels sealed; final-test evaluation requires a frozen procedure.",
    "Locate the gold-ringed validation mistakes in input space. Compare errors near and far from the current decision boundary.",
    "Swap the input columns and follow the displaced point and changed probability. A missing second input is rejected instead of guessed.",
    "Choose an architecture mechanism: trace a CNN window, an RNN state through time, or attention weights into a context vector.",
    "Move one input and predict which side of the boundary it will occupy. Compare its probability before and after training.",
    "Complete one ordered cycle, rewind it, and replay it. Match the visual phase to the unchanged or updated model parameters.",
  ],
  "deep-learning": [
    "Keep the apple image fixed. Compare an image label, a location box and a pixel mask: each task asks for a different output.",
    "Change only the background. The illustrated shortcut rule changes its prediction even though the apple is identical.",
    "Inspect the disjoint training, validation and test groups. Only training examples may update weights or fit preprocessing.",
    "Select a pixel address. Find its entry in the array, then count how eight examples create a batch of 200 numbers.",
    "Change one input or weight. Follow multiplication, addition of bias and the nonlinear activation as separate numerical operations.",
    "Move the edge filter over the image patch. Compare its raw feature response with the response after ReLU; these are explicit teaching filters.",
    "Step through forward prediction, loss, gradients and update. Check that the gradient exists before any weights move.",
    "Compare all-unit evaluation with the fixed dropout mask. See the removed hidden response and its effect on the combined prediction.",
    "Trace one complete local mechanism: CNN products and sum, RNN carried state, or attention’s weighted-average context vector.",
    "Toggle whether the later backbone is trainable. Early features remain frozen; the new task head is trainable in both settings.",
    "Inspect validation errors by actual and predicted class. Test rows remain sealed until a final evaluation procedure is fixed.",
    "Swap feature order or remove a required input. Trace the resulting coordinate change or rejection, then restore the saved contract.",
  ],
};
